-- Oferta 2026-2: 761 pares, 1 salen.
-- GENERADO por `pnpm generate-offer`. No editar a mano.

insert into public.course_teachers (course_code, teacher_email, teacher_name) values
  ('AD2003', 'mlunga@utec.edu.pe', 'Lunga Calderon, Milagros Cecilia'),
  ('AD2007', 'ikalinowski@utec.edu.pe', 'Kalinowski Castillo, Ivo Marek'),
  ('AD2008', 'jaguilar@utec.edu.pe', 'Aguilar Alfaro, José Manuel'),
  ('AD2009', 'pperezq@utec.edu.pe', 'Perez Quineche, Pablo Andres'),
  ('AD2011', 'exicota@utec.edu.pe', 'XICOTA TORRES, ESTER'),
  ('AD3001', 'jaguilar@utec.edu.pe', 'Aguilar Alfaro, José Manuel'),
  ('AD3002', 'rcondorena@utec.edu.pe', 'Condorena Franco, Rodolfo del Carmen'),
  ('AD3003', 'mlunga@utec.edu.pe', 'Lunga Calderon, Milagros Cecilia'),
  ('AD3004', 'lsalazar@utec.edu.pe', 'Salazar Alvarado, Luis Carlos'),
  ('AD3005', 'fcastillo@utec.edu.pe', 'Castillo Castillo, Fabrizio Julio'),
  ('AD3006', 'lgomez@utec.edu.pe', 'Gomez Bustamante, Luis'),
  ('AD3010', 'amorantep@utec.edu.pe', 'Morante Ponce, Alan Victor Raul'),
  ('AD3014', 'dramirez@utec.edu.pe', 'Ramirez Fonseca, Diana Estefania'),
  ('AD3015', 'smontoya@utec.edu.pe', 'Montoya Alarcon De Hamoir, Sheyla Rosa'),
  ('AD3017', 'sarevalo@utec.edu.pe', 'Arevalo Ventocilla, Silvanna'),
  ('AD3018', 'gvargas@utec.edu.pe', 'Vargas De La Guarda, Guillermo Gabriel'),
  ('AD3108', 'sotero@utec.edu.pe', 'Otero Vargas, Sebastian'),
  ('AD4001', 'aestrada@utec.edu.pe', 'Estrada Merino, Alfredo'),
  ('AD4002', 'zgallegos@utec.edu.pe', 'Gallegos Caldas, Zaida Gabriela'),
  ('AD4003', 'iorbegoso@utec.edu.pe', 'Orbegoso Salas, Istavay Alberto'),
  ('AD4004', 'anue@utec.edu.pe', 'Nue Lozada, Augusto Pedro'),
  ('AD4016', 'arojasd@utec.edu.pe', 'Rojas Delgado, Antonio Mitchell'),
  ('AD4301', 'flache@utec.edu.pe', 'Lache Saldaña, Fernando Alan Raul'),
  ('AD4305', 'jaguilar@utec.edu.pe', 'Aguilar Alfaro, José Manuel'),
  ('AD4307', 'kneira@utec.edu.pe', 'Neira Neira, Kenny'),
  ('AD4403', 'kneira@utec.edu.pe', 'Neira Neira, Kenny'),
  ('AD5001', 'kneira@utec.edu.pe', 'Neira Neira, Kenny'),
  ('AD5002', 'owong@utec.edu.pe', 'Wong Loo, Oscar William Francisco'),
  ('AD5003', 'kgranda@utec.edu.pe', 'Granda Escajadillo, Kevin André'),
  ('AD5004', 'sarevalo@utec.edu.pe', 'Arevalo Ventocilla, Silvanna'),
  ('AD5018', 'amorantep@utec.edu.pe', 'Morante Ponce, Alan Victor Raul'),
  ('AD5019', 'cmarquezm@utec.edu.pe', 'Marquez Mercado, Carlos Enrique'),
  ('AD5114', 'ttijero@utec.edu.pe', 'Tijero Neyra, Talia Elena'),
  ('AD6001', 'ehernandez@utec.edu.pe', 'Hernández Pacheco, Edgar Javier'),
  ('AD6002', 'lobispo@utec.edu.pe', 'Obispo Sotomayor, Lester Alberto'),
  ('AD6003', 'dluna@utec.edu.pe', 'Luna Torres, Diana Maria'),
  ('AD6005', 'ikalinowski@utec.edu.pe', 'Kalinowski Castillo, Ivo Marek'),
  ('AD6006', 'mlunga@utec.edu.pe', 'Lunga Calderon, Milagros Cecilia'),
  ('AD6007', 'lobispo@utec.edu.pe', 'Obispo Sotomayor, Lester Alberto'),
  ('AD6032', 'kneira@utec.edu.pe', 'Neira Neira, Kenny'),
  ('AD6100', 'fvilela@utec.edu.pe', 'VILELA LOPEZ, FERNANDO JAIME'),
  ('AD6100', 'jvalencia@utec.edu.pe', 'Valencia Zapata, Julian'),
  ('AD6100', 'kneira@utec.edu.pe', 'Neira Neira, Kenny'),
  ('AM1003', 'mlatorre@utec.edu.pe', 'La Torre Cuadros, Maria de los Angeles'),
  ('AM2001', 'mfloresf@utec.edu.pe', 'Flores Flores, Myra'),
  ('AM2003', 'evereau@utec.edu.pe', 'Vereau Miranda, Edmundo'),
  ('AM2003', 'rguerra@utec.edu.pe', 'Guerra LLANOS, Renzo Alejandro'),
  ('AM2004', 'cmillan@utec.edu.pe', 'Millan Arancibia, Carlos Enrique'),
  ('AM3001', 'hllauca@utec.edu.pe', 'Llauca Soto, Harold Omar'),
  ('AM3001', 'kdelgado@utec.edu.pe', 'Delgado Villanueva, Kiko Alexi'),
  ('AM3002', 'jmendozam@utec.edu.pe', 'Mendoza Montalvo, Jimmy'),
  ('AM3003', 'irabitsch@utec.edu.pe', 'Rabitsch Musso, Ingrid'),
  ('AM3005', 'mporlles@utec.edu.pe', 'Porlles Arteaga, Mirjana Alice'),
  ('AM3006', 'kdelgado@utec.edu.pe', 'Delgado Villanueva, Kiko Alexi'),
  ('AM3007', 'lchuquisengo@utec.edu.pe', 'Chuquisengo Picon, Llojan'),
  ('AM4002', 'ahijar@utec.edu.pe', 'Hijar Santibañez, Alfredo'),
  ('AM4003', 'mriverac@utec.edu.pe', 'Rivera Charun, Maria  Lucia'),
  ('AM4301', 'mlatorre@utec.edu.pe', 'La Torre Cuadros, Maria de los Angeles'),
  ('AM4302', 'imontes@utec.edu.pe', 'Montes Torres, Ivonne Katherine'),
  ('AM4303', 'mriverac@utec.edu.pe', 'Rivera Charun, Maria  Lucia'),
  ('AM4304', 'rguerra@utec.edu.pe', 'Guerra LLANOS, Renzo Alejandro'),
  ('AM4305', 'acongrains@utec.edu.pe', 'CONGRAINS CASTILLO, ADA'),
  ('AM4308', 'gmonge@utec.edu.pe', 'Monge Talavera, Gladys Elena'),
  ('AM4311', 'schero@utec.edu.pe', 'CHERO OSORIO, SHEYLA PAOLA'),
  ('AM4314', 'cmillan@utec.edu.pe', 'Millan Arancibia, Carlos Enrique'),
  ('AM4315', 'jzevallosr@utec.edu.pe', 'Zevallos Ruiz, Jose Augusto'),
  ('AM5001', 'kdelgado@utec.edu.pe', 'Delgado Villanueva, Kiko Alexi'),
  ('AM5002', 'janicama@utec.edu.pe', 'Anicama Díaz, Jahir'),
  ('AM5007', 'kdelgado@utec.edu.pe', 'Delgado Villanueva, Kiko Alexi'),
  ('AM5106', 'kdelgado@utec.edu.pe', 'Delgado Villanueva, Kiko Alexi'),
  ('AM5106', 'mriverac@utec.edu.pe', 'Rivera Charun, Maria  Lucia'),
  ('AM6101', 'kdelgado@utec.edu.pe', 'Delgado Villanueva, Kiko Alexi'),
  ('AM6102', 'mfloresf@utec.edu.pe', 'Flores Flores, Myra'),
  ('AM6103', 'evereau@utec.edu.pe', 'Vereau Miranda, Edmundo'),
  ('BA6001', 'jsaldana@utec.edu.pe', 'Saldaña Cortes, Jenny Carolina'),
  ('BI1002', 'mcueva@utec.edu.pe', 'Cueva Tavara, Mario'),
  ('BI2004', 'jbanon@utec.edu.pe', 'Bañon Arias, Jonnatan Victor'),
  ('BI3005', 'hsaavedra@utec.edu.pe', 'SAAVEDRA ESPINOZA, HARRY GUSTAVO'),
  ('BI3005', 'jhuacachi@utec.edu.pe', 'HUACACHI BAZAN, JOSE GABRIEL'),
  ('BI3006', 'mcueva@utec.edu.pe', 'Cueva Tavara, Mario'),
  ('BI3007', 'cfranco@utec.edu.pe', 'Franco Acosta, Christian Martin'),
  ('BI3008', 'aagapito@utec.edu.pe', 'Agapito Cordova, Alonso'),
  ('BI3009', 'aariasm@utec.edu.pe', 'Arias Moreno, Andrés Julián'),
  ('BI3009', 'acordovar@utec.edu.pe', 'Cordova Rodriguez, Anthony Raul'),
  ('BI3010', 'mcueva@utec.edu.pe', 'Cueva Tavara, Mario'),
  ('BI4011', 'aquispeg@utec.edu.pe', 'Quispe Gutierrez, Antonio Marty'),
  ('BI4012', 'pcardenas@utec.edu.pe', 'Cardenas Lizana, Paul Antonio'),
  ('BI4012', 'tcajahuanca@utec.edu.pe', 'CAJAHUANCA HUACCHO, TITO MARTIN'),
  ('BI4013', 'ljaramillo@utec.edu.pe', 'Jaramillo Valverde, Luis Jose'),
  ('BI4014', 'hmanriquec@utec.edu.pe', 'Manrique Chicoma, Hugo'),
  ('BI4430', 'acollantes@utec.edu.pe', 'Collantes Biggio, Andrea del Pilar'),
  ('BI4431', 'jvaldivias@utec.edu.pe', 'Valdivia Silva, Julio Ernesto'),
  ('BI4432', 'acollantes@utec.edu.pe', 'Collantes Biggio, Andrea del Pilar'),
  ('BI4433', 'ljaramillo@utec.edu.pe', 'Jaramillo Valverde, Luis Jose'),
  ('BI4434', 'mcueva@utec.edu.pe', 'Cueva Tavara, Mario'),
  ('BI4435', 'gsandoval@utec.edu.pe', 'Sandoval Lozano, Giovani'),
  ('BI4439', 'aratti@utec.edu.pe', 'Ratti Parandelli, Alejandra'),
  ('BI4439', 'gtravi@utec.edu.pe', 'Travi Antonio, Giulianna'),
  ('BI5009', 'hsaavedra@utec.edu.pe', 'SAAVEDRA ESPINOZA, HARRY GUSTAVO'),
  ('BI5009', 'jlezama@utec.edu.pe', 'Lezama Calvo, Jinmi'),
  ('BI5009', 'mclemente@utec.edu.pe', 'Clemente Arenas, Mark Donny'),
  ('BI5009', 'pcrisostomo@utec.edu.pe', 'Crisostomo Romero, Pedro Moises'),
  ('BI5015', 'mclemente@utec.edu.pe', 'Clemente Arenas, Mark Donny'),
  ('BI5016', 'adonayre@utec.edu.pe', 'Donayre Torres, Alberto Jesus'),
  ('BI5016', 'jhuacachi@utec.edu.pe', 'HUACACHI BAZAN, JOSE GABRIEL'),
  ('BI5108', 'aariasm@utec.edu.pe', 'Arias Moreno, Andrés Julián'),
  ('BI5108', 'jlezama@utec.edu.pe', 'Lezama Calvo, Jinmi'),
  ('BI5108', 'pcardenas@utec.edu.pe', 'Cardenas Lizana, Paul Antonio'),
  ('BI5318', 'pcrisostomo@utec.edu.pe', 'Crisostomo Romero, Pedro Moises'),
  ('BI5319', 'sflores@utec.edu.pe', 'Flores Daorta, Sthy  Warren'),
  ('BI5320', 'lgamarra@utec.edu.pe', 'Gamarra Contreras, Lionel Fernel'),
  ('BI5321', 'jfranco@utec.edu.pe', 'Franco Salinas, Joana Cristina'),
  ('BI5322', 'jfranco@utec.edu.pe', 'Franco Salinas, Joana Cristina'),
  ('BI5323', 'acardenasr@utec.edu.pe', 'Cárdenas Rivera, Alfredo'),
  ('BI5324', 'jbanon@utec.edu.pe', 'Bañon Arias, Jonnatan Victor'),
  ('BI5325', 'adonayre@utec.edu.pe', 'Donayre Torres, Alberto Jesus'),
  ('BI5326', 'adonayre@utec.edu.pe', 'Donayre Torres, Alberto Jesus'),
  ('BI5327', 'kgonzales@utec.edu.pe', 'Gonzales Rojas, Karen'),
  ('BI5328', 'lperez@utec.edu.pe', 'PEREZ TULICH, LUZ NARCIZA MERCEDES'),
  ('BI6001', 'mcueva@utec.edu.pe', 'Cueva Tavara, Mario'),
  ('BI6002', 'mcueva@utec.edu.pe', 'Cueva Tavara, Mario'),
  ('BI6003', 'cfranco@utec.edu.pe', 'Franco Acosta, Christian Martin'),
  ('CC1101', 'crojas@utec.edu.pe', 'Rojas Huamán, Cristian Felix'),
  ('CC1101', 'preynoso@utec.edu.pe', 'Reynoso Quispe, Patricia'),
  ('CC1101', 'volivera@utec.edu.pe', 'Olivera Oliva, Davy Alonso'),
  ('CC1102', 'cnavarro@utec.edu.pe', 'Navarro Flores, Cristina'),
  ('CC1103', 'eanco@utec.edu.pe', 'Anco Blas, Edith Chavely'),
  ('CC1103', 'hpantoja@utec.edu.pe', 'Pantoja Carhuavilca, Hermes Yesser'),
  ('CC1103', 'rperezc@utec.edu.pe', 'Perez Cupe, Rosulo'),
  ('CC1103', 'xchavez@utec.edu.pe', 'Chavez Pacheco, Xyoby'),
  ('CC1104', 'apena@utec.edu.pe', 'Peña Nevado, Alexander Filadelfo'),
  ('CC1104', 'ctorresf@utec.edu.pe', 'Torres Fernandez, Carlos Enrique'),
  ('CC1104', 'preynoso@utec.edu.pe', 'Reynoso Quispe, Patricia'),
  ('CC1105', 'agamero@utec.edu.pe', 'Gamero Paredes, Antonio Alejandro'),
  ('CC1105', 'dgallo@utec.edu.pe', 'Gallo Torres, Dante Jim Randal'),
  ('CC1105', 'jrenom@utec.edu.pe', 'Renom Andara, Jose Miguel'),
  ('CC1105', 'mprado@utec.edu.pe', 'Prado Urbano, Mariano Ignacio'),
  ('CC1105', 'msaenz@utec.edu.pe', 'Sáenz Egúsquiza, Miguel Ángel'),
  ('CC1105', 'ogalarza@utec.edu.pe', 'Galarza Geronimo, Orlando Alfredo'),
  ('CC1105', 'stanay@utec.edu.pe', 'TANAY, SASHWAT'),
  ('CC1122', 'elay@utec.edu.pe', 'Lay Mesones, Enrique'),
  ('CC1122', 'jsanchezr@utec.edu.pe', 'Sanchez Romero, José Renato'),
  ('CC1122', 'mmendozaf@utec.edu.pe', 'Mendoza Flores, Miguel Alberto'),
  ('CC1123', 'mcuyubamba@utec.edu.pe', 'Cuyubamba Espinoza, Marco Antonio'),
  ('CC1123', 'ocastillo@utec.edu.pe', 'Castillo Ruiz, Oscar Eduardo'),
  ('CC1141', 'mluna@utec.edu.pe', 'Luna Quinto, Miguel Alexis'),
  ('CC1141', 'rhoyos@utec.edu.pe', 'Hoyos Diaz, Rocío Giovanna'),
  ('CC1142', 'cfranco@utec.edu.pe', 'Franco Acosta, Christian Martin'),
  ('CC1143', 'arios@utec.edu.pe', 'Rios Cuadros, Alejandro'),
  ('CC2101', 'cnavarro@utec.edu.pe', 'Navarro Flores, Cristina'),
  ('CC2101', 'jgalvezg@utec.edu.pe', 'Gálvez Ghersi, José Tomás'),
  ('CC2101', 'jsanchezr@utec.edu.pe', 'Sanchez Romero, José Renato'),
  ('CC2101', 'mcuyubamba@utec.edu.pe', 'Cuyubamba Espinoza, Marco Antonio'),
  ('CC2101', 'nlopez@utec.edu.pe', 'Lopez Rodriguez, Naudy Ricardo'),
  ('CC2101', 'preynoso@utec.edu.pe', 'Reynoso Quispe, Patricia'),
  ('CC2102', 'ogalarza@utec.edu.pe', 'Galarza Geronimo, Orlando Alfredo'),
  ('CC2103', 'fvivanco@utec.edu.pe', 'Vivanco Huaytara, Fredy'),
  ('CC2104', 'jmendozam@utec.edu.pe', 'Mendoza Montalvo, Jimmy'),
  ('CC2104', 'mcuyubamba@utec.edu.pe', 'Cuyubamba Espinoza, Marco Antonio'),
  ('CC2104', 'preynoso@utec.edu.pe', 'Reynoso Quispe, Patricia'),
  ('CC2104', 'rperezc@utec.edu.pe', 'Perez Cupe, Rosulo'),
  ('CC2106', 'fvivanco@utec.edu.pe', 'Vivanco Huaytara, Fredy'),
  ('CC2121', 'ctorresf@utec.edu.pe', 'Torres Fernandez, Carlos Enrique'),
  ('CC2121', 'nlopez@utec.edu.pe', 'Lopez Rodriguez, Naudy Ricardo'),
  ('CC2121', 'nsanchezr@utec.edu.pe', 'Sanchez Ramirez, Nedher'),
  ('CC6101', 'ckhouri@utec.edu.pe', 'Khouri De Arciniegas, Cordelia'),
  ('CC6101', 'cnavarro@utec.edu.pe', 'Navarro Flores, Cristina'),
  ('CC6101', 'crojas@utec.edu.pe', 'Rojas Huamán, Cristian Felix'),
  ('CC6101', 'ctorresf@utec.edu.pe', 'Torres Fernandez, Carlos Enrique'),
  ('CC6101', 'jchiroque@utec.edu.pe', 'Chiroque Calderon, Jorge Luis'),
  ('CC6101', 'jnieves@utec.edu.pe', 'Nieves Diaz, Jose Ignacio'),
  ('CC6101', 'mcuyubamba@utec.edu.pe', 'Cuyubamba Espinoza, Marco Antonio'),
  ('CC6101', 'volivera@utec.edu.pe', 'Olivera Oliva, Davy Alonso'),
  ('CC6102', 'jnieves@utec.edu.pe', 'Nieves Diaz, Jose Ignacio'),
  ('CC6103', 'crojas@utec.edu.pe', 'Rojas Huamán, Cristian Felix'),
  ('CC6103', 'eanco@utec.edu.pe', 'Anco Blas, Edith Chavely'),
  ('CC6103', 'preynoso@utec.edu.pe', 'Reynoso Quispe, Patricia'),
  ('CC6103', 'rperezc@utec.edu.pe', 'Perez Cupe, Rosulo'),
  ('CC6103', 'rseclen@utec.edu.pe', 'Seclen Campos, Rolando Roberto'),
  ('CC6103', 'squispe@utec.edu.pe', 'Quispe Rodriguez, Sergio'),
  ('CC6103', 'volivera@utec.edu.pe', 'Olivera Oliva, Davy Alonso'),
  ('CC6103', 'xchavez@utec.edu.pe', 'Chavez Pacheco, Xyoby'),
  ('CC6104', 'volivera@utec.edu.pe', 'Olivera Oliva, Davy Alonso'),
  ('CC6105', 'eanco@utec.edu.pe', 'Anco Blas, Edith Chavely'),
  ('CC6105', 'hpantoja@utec.edu.pe', 'Pantoja Carhuavilca, Hermes Yesser'),
  ('CC6105', 'jbarraza@utec.edu.pe', 'Barraza Bernaola, Julio Cesar'),
  ('CC6105', 'oortiz@utec.edu.pe', 'Ortiz Cabello, Omar Hernan'),
  ('CC6105', 'xchavez@utec.edu.pe', 'Chavez Pacheco, Xyoby'),
  ('CC6201', 'cmouls@utec.edu.pe', 'Mouls, Caroline'),
  ('CC6201', 'jsanchezr@utec.edu.pe', 'Sanchez Romero, José Renato'),
  ('CC6201', 'kzegarras@utec.edu.pe', 'Zegarra Sierra, Katia'),
  ('CC6201', 'ocastillo@utec.edu.pe', 'Castillo Ruiz, Oscar Eduardo'),
  ('CC6301', 'apinedo@utec.edu.pe', 'Pinedo Flores, Angela'),
  ('CC6301', 'cfranco@utec.edu.pe', 'Franco Acosta, Christian Martin'),
  ('CC6301', 'cterrones@utec.edu.pe', 'Terrones Sanchez, Cindy Carolina'),
  ('CC6301', 'hcarcamo@utec.edu.pe', 'Carcamo Cabrera, Henry Alonso'),
  ('CC6301', 'jgonzales@utec.edu.pe', 'Gonzales Balladares, Julio'),
  ('CC6301', 'layala@utec.edu.pe', 'Ayala Correa, Luis Jair'),
  ('CC6301', 'rhoyos@utec.edu.pe', 'Hoyos Diaz, Rocío Giovanna'),
  ('CI2003', 'mfernandezch@utec.edu.pe', 'Fernandez Choquepuma, Miguel Angel'),
  ('CI2011', 'aostolaza@utec.edu.pe', 'Ostolaza Cantuarias, Arianne'),
  ('CI2011', 'cdiaze@utec.edu.pe', 'Diaz Esquivel, Christian Manuel'),
  ('CI2012', 'cdiaze@utec.edu.pe', 'Diaz Esquivel, Christian Manuel'),
  ('CI2031', 'ejuarez@utec.edu.pe', 'Juarez Aquino, Enrique'),
  ('CI3013', 'aostolaza@utec.edu.pe', 'Ostolaza Cantuarias, Arianne'),
  ('CI3014', 'aostolaza@utec.edu.pe', 'Ostolaza Cantuarias, Arianne'),
  ('CI3032', 'gperez@utec.edu.pe', 'Perez Garavito, Gian Franco'),
  ('CI3032', 'rvasqueza@utec.edu.pe', 'Vasquez Arrieta, Elba Rosaura'),
  ('CI3033', 'msalas@utec.edu.pe', 'Salas Paulet, Manuel Jesus'),
  ('CI3051', 'aarones@utec.edu.pe', 'Arones Villavicencio, Alvaro Paulo'),
  ('CI3071', 'cramos@utec.edu.pe', 'Ramos Orlandino, Carmela Cristhy'),
  ('CI3071', 'jmendozam@utec.edu.pe', 'Mendoza Montalvo, Jimmy'),
  ('CI4034', 'hsuarezt@utec.edu.pe', 'Suarez Torres, Harold Alberto'),
  ('CI4035', 'hpineda@utec.edu.pe', 'Pineda Vallejo, Hugo Esteban'),
  ('CI4052', 'mtincopa@utec.edu.pe', 'Tincopa Heredia, Mayu Alberto'),
  ('CI4072', 'eguzman@utec.edu.pe', 'Guzman Zorrilla, Emanuel Jesus'),
  ('CI4092', 'asanchezn@utec.edu.pe', 'Sanchez Navarro, Alex Manuel'),
  ('CI5006', 'cdiaze@utec.edu.pe', 'Diaz Esquivel, Christian Manuel'),
  ('CI5006', 'ejuarez@utec.edu.pe', 'Juarez Aquino, Enrique'),
  ('CI5006', 'gsotoc@utec.edu.pe', 'Soto Caldas, Grethell Gladys Maria'),
  ('CI5006', 'hpineda@utec.edu.pe', 'Pineda Vallejo, Hugo Esteban'),
  ('CI5006', 'hsuarezt@utec.edu.pe', 'Suarez Torres, Harold Alberto'),
  ('CI5006', 'jorccosupa@utec.edu.pe', 'Orccosupa Rivera, Javier'),
  ('CI5006', 'lbedrinana@utec.edu.pe', 'Bedriñana Mera, Luis Alberto'),
  ('CI5093', 'mfernandezch@utec.edu.pe', 'Fernandez Choquepuma, Miguel Angel'),
  ('CI5105', 'aostolaza@utec.edu.pe', 'Ostolaza Cantuarias, Arianne'),
  ('CI5105', 'asanchezn@utec.edu.pe', 'Sanchez Navarro, Alex Manuel'),
  ('CI5105', 'cbenedetty@utec.edu.pe', 'Benedetty Torres, Carlos Alberto'),
  ('CI5105', 'cdiaze@utec.edu.pe', 'Diaz Esquivel, Christian Manuel'),
  ('CI5105', 'ejuarez@utec.edu.pe', 'Juarez Aquino, Enrique'),
  ('CI5105', 'evereau@utec.edu.pe', 'Vereau Miranda, Edmundo'),
  ('CI5105', 'hpineda@utec.edu.pe', 'Pineda Vallejo, Hugo Esteban'),
  ('CI5105', 'hsuarezt@utec.edu.pe', 'Suarez Torres, Harold Alberto'),
  ('CI5105', 'mfernandezch@utec.edu.pe', 'Fernandez Choquepuma, Miguel Angel'),
  ('CI5105', 'mjara@utec.edu.pe', 'Jara Garcia, Mitchel Jimmy'),
  ('CI5105', 'rgutierrezl@utec.edu.pe', 'Gutierrez Llantoy, Ronald Roger'),
  ('CI5311', 'cbenedetty@utec.edu.pe', 'Benedetty Torres, Carlos Alberto'),
  ('CI5312', 'cdiaze@utec.edu.pe', 'Diaz Esquivel, Christian Manuel'),
  ('CI5313', 'cdiaze@utec.edu.pe', 'Diaz Esquivel, Christian Manuel'),
  ('CI5314', 'aostolaza@utec.edu.pe', 'Ostolaza Cantuarias, Arianne'),
  ('CI5331', 'hsuarezt@utec.edu.pe', 'Suarez Torres, Harold Alberto'),
  ('CI5332', 'dpolanco@utec.edu.pe', 'Polanco Lopez, Doris Patricia'),
  ('CI5333', 'ejuarez@utec.edu.pe', 'Juarez Aquino, Enrique'),
  ('CI5335', 'hsuarezt@utec.edu.pe', 'Suarez Torres, Harold Alberto'),
  ('CI5336', 'emejias@utec.edu.pe', 'Mejia Solis, Enrique'),
  ('CI5351', 'lraygada@utec.edu.pe', 'Raygada Rojas, Luis Fernando'),
  ('CI5353', 'lnunezn@utec.edu.pe', 'Nuñez Novara, Luis Alfredo'),
  ('CI5372', 'eguzman@utec.edu.pe', 'Guzman Zorrilla, Emanuel Jesus'),
  ('CI5373', 'mjara@utec.edu.pe', 'Jara Garcia, Mitchel Jimmy'),
  ('CI5391', 'mfernandezch@utec.edu.pe', 'Fernandez Choquepuma, Miguel Angel'),
  ('CI5394', 'wsamaniego@utec.edu.pe', 'Samaniego Barja, Walter'),
  ('CI5395', 'wsamaniego@utec.edu.pe', 'Samaniego Barja, Walter'),
  ('CI5396', 'rrojasma@utec.edu.pe', 'Rojas Malasquez, Royer Edelwer'),
  ('CI6101', 'hsuarezt@utec.edu.pe', 'Suarez Torres, Harold Alberto'),
  ('CI6102', 'kvilela@utec.edu.pe', 'Vilela Manyari, Karina Elizabeth'),
  ('CS2013', 'jchaveza@utec.edu.pe', 'Chavez Alvarez, Jose Armando'),
  ('CS2013', 'rrivas@utec.edu.pe', 'Rivas Medina, Rubén Demetrio'),
  ('CS2023', 'lromeroc@utec.edu.pe', 'ROMERO CALLA, LUCIANO ARNALDO'),
  ('CS2023', 'vgalvan@utec.edu.pe', 'Galvan Oyola, Victor Racso'),
  ('CS2023', 'wnina@utec.edu.pe', 'Nina Choquehuayta, Wilder'),
  ('CS2031', 'jvillavicencio@utec.edu.pe', 'Villavicencio Antunez, Jorge'),
  ('CS2031', 'jyarascam@utec.edu.pe', 'Yarasca Moscol, Julio Eduardo'),
  ('CS2031', 'plovon@utec.edu.pe', 'Lovon Ramos, Percy Wilianson'),
  ('CS2032', 'gcolchado@utec.edu.pe', 'Colchado Ruíz, Geraldo'),
  ('CS2032', 'omejia@utec.edu.pe', 'Mejia Fernandez, Oscar Rodolfo'),
  ('CS2041', 'bojeda@utec.edu.pe', 'Ojeda Rios, Brenner Humberto'),
  ('CS2041', 'wnina@utec.edu.pe', 'Nina Choquehuayta, Wilder'),
  ('CS2042', 'hsanchez@utec.edu.pe', 'Sanchez Enriquez, Heider Ysaias'),
  ('CS2042', 'plovon@utec.edu.pe', 'Lovon Ramos, Percy Wilianson'),
  ('CS3014', 'vgalvan@utec.edu.pe', 'Galvan Oyola, Victor Racso'),
  ('CS3015', 'jgonzalez@utec.edu.pe', 'Gonzalez Reaño, Jorge Luis'),
  ('CS3025', 'jyarascam@utec.edu.pe', 'Yarasca Moscol, Julio Eduardo'),
  ('CS3026', 'jgalva@utec.edu.pe', 'Gutierrez Alva, Julio'),
  ('CS3026', 'vgalvan@utec.edu.pe', 'Galvan Oyola, Victor Racso'),
  ('CS3033', 'vgalvan@utec.edu.pe', 'Galvan Oyola, Victor Racso'),
  ('CS3051', 'cwilliams@utec.edu.pe', 'Williams Valencia, Carlos Eduardo'),
  ('CS3051', 'jgonzalez@utec.edu.pe', 'Gonzalez Reaño, Jorge Luis'),
  ('CS3051', 'ladanaque@utec.edu.pe', 'Adanaque Infante, Luz Antuanet'),
  ('CS3061', 'vmartinez@utec.edu.pe', 'Martinez Abaunza, Victor Eduardo'),
  ('CS3081', 'tchambilla@utec.edu.pe', 'Chambilla Aquino, Teófilo'),
  ('CS4052', 'jfiestas@utec.edu.pe', 'Fiestas Iquira, Jose Antonio'),
  ('CS4053', 'tchambilla@utec.edu.pe', 'Chambilla Aquino, Teófilo'),
  ('CS4054', 'cwilliams@utec.edu.pe', 'Williams Valencia, Carlos Eduardo'),
  ('CS4054', 'garias@utec.edu.pe', 'Arias Obregon, Gabriel Andres'),
  ('CS5011', 'avillegass@utec.edu.pe', 'Villegas Suárez, Ariana Mirella'),
  ('CS5011', 'bojeda@utec.edu.pe', 'Ojeda Rios, Brenner Humberto'),
  ('CS5011', 'clopezd@utec.edu.pe', 'Lopez Del Alamo, Cristian Jose'),
  ('CS5011', 'ctenorio@utec.edu.pe', 'TENORIO GONZALES, CANDY VERONICA'),
  ('CS5011', 'ebiagioli@utec.edu.pe', 'Biagioli, Eric Javier'),
  ('CS5011', 'ecayllahua@utec.edu.pe', 'Cayllahua Cahuina, Edward Jorge Yuri'),
  ('CS5011', 'jchaveza@utec.edu.pe', 'Chavez Alvarez, Jose Armando'),
  ('CS5011', 'jfiestas@utec.edu.pe', 'Fiestas Iquira, Jose Antonio'),
  ('CS5011', 'jgonzalez@utec.edu.pe', 'Gonzalez Reaño, Jorge Luis'),
  ('CS5011', 'ladanaque@utec.edu.pe', 'Adanaque Infante, Luz Antuanet'),
  ('CS5011', 'lromeroc@utec.edu.pe', 'ROMERO CALLA, LUCIANO ARNALDO'),
  ('CS5011', 'rmora@utec.edu.pe', 'Mora Cloque, Rensso Victor Hugo'),
  ('CS5011', 'vflores@utec.edu.pe', 'Flores Benites, Victor'),
  ('CS5011', 'vmartinez@utec.edu.pe', 'Martinez Abaunza, Victor Eduardo'),
  ('CS5055', 'cwilliams@utec.edu.pe', 'Williams Valencia, Carlos Eduardo'),
  ('CS5055', 'garias@utec.edu.pe', 'Arias Obregon, Gabriel Andres'),
  ('CS5101', 'avillegass@utec.edu.pe', 'Villegas Suárez, Ariana Mirella'),
  ('CS5101', 'bojeda@utec.edu.pe', 'Ojeda Rios, Brenner Humberto'),
  ('CS5101', 'clopezd@utec.edu.pe', 'Lopez Del Alamo, Cristian Jose'),
  ('CS5101', 'ctenorio@utec.edu.pe', 'TENORIO GONZALES, CANDY VERONICA'),
  ('CS5101', 'ebiagioli@utec.edu.pe', 'Biagioli, Eric Javier'),
  ('CS5101', 'ecayllahua@utec.edu.pe', 'Cayllahua Cahuina, Edward Jorge Yuri'),
  ('CS5101', 'hgallegos@utec.edu.pe', 'Gallegos Velgara, Henry Giovanny'),
  ('CS5101', 'jchaveza@utec.edu.pe', 'Chavez Alvarez, Jose Armando'),
  ('CS5101', 'jfiestas@utec.edu.pe', 'Fiestas Iquira, Jose Antonio'),
  ('CS5101', 'jgonzalez@utec.edu.pe', 'Gonzalez Reaño, Jorge Luis'),
  ('CS5101', 'ladanaque@utec.edu.pe', 'Adanaque Infante, Luz Antuanet'),
  ('CS5101', 'lromeroc@utec.edu.pe', 'ROMERO CALLA, LUCIANO ARNALDO'),
  ('CS5101', 'rmora@utec.edu.pe', 'Mora Cloque, Rensso Victor Hugo'),
  ('CS5101', 'tchambilla@utec.edu.pe', 'Chambilla Aquino, Teófilo'),
  ('CS5101', 'vflores@utec.edu.pe', 'Flores Benites, Victor'),
  ('CS5101', 'vmartinez@utec.edu.pe', 'Martinez Abaunza, Victor Eduardo'),
  ('CS5101', 'wnina@utec.edu.pe', 'Nina Choquehuayta, Wilder'),
  ('CS5351', 'ebiagioli@utec.edu.pe', 'Biagioli, Eric Javier'),
  ('CS5352', 'lromeroc@utec.edu.pe', 'ROMERO CALLA, LUCIANO ARNALDO'),
  ('CS5362', 'rmora@utec.edu.pe', 'Mora Cloque, Rensso Victor Hugo'),
  ('CS5362', 'vmandujano@utec.edu.pe', 'Mandujano Cornejo, Vittorino'),
  ('CS5363', 'asoriano@utec.edu.pe', 'Soriano Vargas, Aurea Rossy'),
  ('CS5364', 'vflores@utec.edu.pe', 'Flores Benites, Victor'),
  ('CS5365', 'jchaveza@utec.edu.pe', 'Chavez Alvarez, Jose Armando'),
  ('CS5371', 'jpazos@utec.edu.pe', 'Pazos Ortiz, Jose Carlos'),
  ('CS5373', 'lgastulo@utec.edu.pe', 'GASTULO SALAZAR, LUIS MIGUEL'),
  ('CS5382', 'cbalbuena@utec.edu.pe', 'Balbuena Palacios, Carlos'),
  ('CS5383', 'crojasb@utec.edu.pe', 'ROJAS BARRAZA, CLUNY JUDIHT'),
  ('CS5384', 'gpajuelo@utec.edu.pe', 'Pajuelo Pardo, Gustavo'),
  ('CS5392', 'jgutierreza@utec.edu.pe', 'Gutierrez Alva, Juan Gabriel'),
  ('CS6001', 'ibrossard@utec.edu.pe', 'Brossard Nuñez, Ian Paul'),
  ('CS6002', 'agarciar@utec.edu.pe', 'Garcia Reyes, Augusto Arturo Luis'),
  ('CS6002', 'hgallegos@utec.edu.pe', 'Gallegos Velgara, Henry Giovanny'),
  ('CS6002', 'jcumpa@utec.edu.pe', 'Cumpa Torres, Jose Moises'),
  ('CS6002', 'jyarascam@utec.edu.pe', 'Yarasca Moscol, Julio Eduardo'),
  ('CS6002', 'mbermejo@utec.edu.pe', 'Bermejo Rios, Maria Hilda'),
  ('CS6003', 'hgallegos@utec.edu.pe', 'Gallegos Velgara, Henry Giovanny'),
  ('CS6003', 'ibrossard@utec.edu.pe', 'Brossard Nuñez, Ian Paul'),
  ('CS6003', 'vmandujano@utec.edu.pe', 'Mandujano Cornejo, Vittorino'),
  ('CS6003', 'wnina@utec.edu.pe', 'Nina Choquehuayta, Wilder'),
  ('CS6004', 'vmandujano@utec.edu.pe', 'Mandujano Cornejo, Vittorino'),
  ('CS6005', 'dsanchezr@utec.edu.pe', 'Sanchez Ruiz, David'),
  ('CS6005', 'etaipe@utec.edu.pe', 'Taipe Huamani, Emerson Lech'),
  ('CS6005', 'jtipe@utec.edu.pe', 'Tipe Villanueva, Jorge'),
  ('CS6005', 'lperes@utec.edu.pe', 'Peres Malarin, Luis Miguel'),
  ('CS6006', 'dsanchezr@utec.edu.pe', 'Sanchez Ruiz, David'),
  ('CS6006', 'lperes@utec.edu.pe', 'Peres Malarin, Luis Miguel'),
  ('CS6006', 'rmas@utec.edu.pe', 'Mas Huaman, Ronald Jesus'),
  ('CY6001', 'jpazos@utec.edu.pe', 'Pazos Ortiz, Jose Carlos'),
  ('CY6001', 'lponce@utec.edu.pe', 'Ponce Contreras, Luis Eduardo'),
  ('DS2011', 'vtorres@utec.edu.pe', 'Torres Castillo, Victor Antonio'),
  ('DS3012', 'jugarte@utec.edu.pe', 'Ugarte Chamorro, Jose Luis'),
  ('DS3021', 'jespinozame@utec.edu.pe', 'Espinoza Melgarejo, Jose Luis'),
  ('DS3022', 'ggarciaz@utec.edu.pe', 'Garcia Zanabria, Germain'),
  ('DS3031', 'jpazos@utec.edu.pe', 'Pazos Ortiz, Jose Carlos'),
  ('DS4051', 'mgarciat@utec.edu.pe', 'Garcia Tenorio, Maryori Flor De Jazmin'),
  ('DS4061', 'dchira@utec.edu.pe', 'Chira Siaden, David Gustavo'),
  ('DS4061', 'mgarciat@utec.edu.pe', 'Garcia Tenorio, Maryori Flor De Jazmin'),
  ('DS4341', 'alezama@utec.edu.pe', 'LEZAMA BENAVIDES, ALDO MARTIN'),
  ('DS5012', 'acardenasm@utec.edu.pe', 'Cardenas Maita, Ana Rocio'),
  ('DS5012', 'asoriano@utec.edu.pe', 'Soriano Vargas, Aurea Rossy'),
  ('DS5012', 'ggarciaz@utec.edu.pe', 'Garcia Zanabria, Germain'),
  ('DS5012', 'rmora@utec.edu.pe', 'Mora Cloque, Rensso Victor Hugo'),
  ('DS5044', 'ytupac@utec.edu.pe', 'Tupac Valdivia, Yvan Jesus'),
  ('DS5102', 'acardenasm@utec.edu.pe', 'Cardenas Maita, Ana Rocio'),
  ('DS5102', 'jgalva@utec.edu.pe', 'Gutierrez Alva, Julio'),
  ('DS5102', 'rmora@utec.edu.pe', 'Mora Cloque, Rensso Victor Hugo'),
  ('DS5342', 'hsanchez@utec.edu.pe', 'Sanchez Enriquez, Heider Ysaias'),
  ('DS5343', 'ggarciaz@utec.edu.pe', 'Garcia Zanabria, Germain'),
  ('DS5344', 'cbalbuena@utec.edu.pe', 'Balbuena Palacios, Carlos'),
  ('DS5345', 'plovon@utec.edu.pe', 'Lovon Ramos, Percy Wilianson'),
  ('DS5346', 'vflores@utec.edu.pe', 'Flores Benites, Victor'),
  ('EL2011', 'jzavalac@utec.edu.pe', 'Zavala Chavez, Jose Gabriel'),
  ('EL2011', 'lquineche@utec.edu.pe', 'Quineche Orellana, Luis Ernesto'),
  ('EL2012', 'gmichhue@utec.edu.pe', 'Michhue Vela, Gabriel Percy'),
  ('EL2012', 'mbelen@utec.edu.pe', 'Belen Contreras, Miguel Angel'),
  ('EL2013', 'ahinostroza@utec.edu.pe', 'Hinostroza Mendoza, Adrián Tomás (Asistente de enseñanza senior)'),
  ('EL2013', 'cbriceno@utec.edu.pe', 'Briceño Carbajal, Christopher Eduardo'),
  ('EL2013', 'fcamacho@utec.edu.pe', 'Camacho Jiménez, Francisco José'),
  ('EL2013', 'gmichhue@utec.edu.pe', 'Michhue Vela, Gabriel Percy'),
  ('EL2013', 'gpatino@utec.edu.pe', 'Patiño Ortega, Giancarlo (Asistente de enseñanza senior)'),
  ('EL2013', 'pcrisostomo@utec.edu.pe', 'Crisostomo Romero, Pedro Moises'),
  ('EL2014', 'iyupanqui@utec.edu.pe', 'Yupanqui Tello, Ivan Francisco'),
  ('EL2014', 'lquineche@utec.edu.pe', 'Quineche Orellana, Luis Ernesto'),
  ('EL2081', 'camaya@utec.edu.pe', 'Amaya Montes, Cristian'),
  ('EL2081', 'earellanos@utec.edu.pe', 'Arellanos Tafur, Elmer Hugo'),
  ('EL2081', 'fcamacho@utec.edu.pe', 'Camacho Jiménez, Francisco José'),
  ('EL2081', 'jzavalac@utec.edu.pe', 'Zavala Chavez, Jose Gabriel'),
  ('EL2081', 'mlozano@utec.edu.pe', 'Lozano Bravo, Miguel Angel'),
  ('EL2082', 'acespedes@utec.edu.pe', 'Cespedes Duran, Axel Eliam'),
  ('EL2082', 'mlozano@utec.edu.pe', 'Lozano Bravo, Miguel Angel'),
  ('EL3011', 'fcamacho@utec.edu.pe', 'Camacho Jiménez, Francisco José'),
  ('EL3012', 'dhuamanchahua@utec.edu.pe', 'Huamanchahua Canchanya, Deyby'),
  ('EL3012', 'hvalcarcel@utec.edu.pe', 'Valcarcel Castillo, Hector Jose'),
  ('EL3012', 'jbautista@utec.edu.pe', 'Bautista Cama, Jose Luis Froilan'),
  ('EL3013', 'cflores@utec.edu.pe', 'Flores Vega, Christian Humberto'),
  ('EL3013', 'jfabianl@utec.edu.pe', 'Fabían Lizárraga, Joao Ulises'),
  ('EL3014', 'fcamacho@utec.edu.pe', 'Camacho Jiménez, Francisco José'),
  ('EL3014', 'gpatino@utec.edu.pe', 'Patiño Ortega, Giancarlo (Asistente de enseñanza senior)'),
  ('EL3014', 'jtarrillo@utec.edu.pe', 'Tarrillo Olano, Jimmy Fernando'),
  ('EL3014', 'nnunovero@utec.edu.pe', 'Nuñovero Cisneros, Nicolas Jose (Asistente de Enseñanza Senior)'),
  ('EL3015', 'mnunez@utec.edu.pe', 'Nuñez Ochoa, Moises'),
  ('EL3016', 'gmichhue@utec.edu.pe', 'Michhue Vela, Gabriel Percy'),
  ('EL3016', 'jlezama@utec.edu.pe', 'Lezama Calvo, Jinmi'),
  ('EL3016', 'mclemente@utec.edu.pe', 'Clemente Arenas, Mark Donny'),
  ('EL3301', 'acespedes@utec.edu.pe', 'Cespedes Duran, Axel Eliam'),
  ('EL3301', 'lgarciaz@utec.edu.pe', 'Garcia Zevallos, Luis Enrique'),
  ('EL3301', 'saranda@utec.edu.pe', 'Aranda Egusquiza, Sergio Rafael'),
  ('EL3302', 'jfarfan@utec.edu.pe', 'Farfán Madariaga, Jaime Moshe'),
  ('EL3303', 'agutarra@utec.edu.pe', 'Gutarra Sanchez, Anthony Gerardo'),
  ('EL3303', 'dinga@utec.edu.pe', 'Inga Narvaez, Dante'),
  ('EL3303', 'smorales@utec.edu.pe', 'Morales Azañedo, Sergio'),
  ('EL3304', 'jfarfan@utec.edu.pe', 'Farfán Madariaga, Jaime Moshe'),
  ('EL4011', 'cmonterrey@utec.edu.pe', 'Monterrey Ikeda, Christian Aaron'),
  ('EL4011', 'mlozano@utec.edu.pe', 'Lozano Bravo, Miguel Angel'),
  ('EL4012', 'lvolodina@utec.edu.pe', 'Volodina Egorovna de Denegri,  Ludmila'),
  ('EL4013', 'framirez@utec.edu.pe', 'Ramirez Horna, Flavio Cesar'),
  ('EL4301', 'cdiazp@utec.edu.pe', 'Diaz Pozzuoli, Carlos Francisco'),
  ('EL4301', 'lgarciaz@utec.edu.pe', 'Garcia Zevallos, Luis Enrique'),
  ('EL4301', 'rcabrerad@utec.edu.pe', 'Cabrera Donayre, Rony Martin'),
  ('EL4302', 'cbriceno@utec.edu.pe', 'Briceño Carbajal, Christopher Eduardo'),
  ('EL4302', 'jtarrillo@utec.edu.pe', 'Tarrillo Olano, Jimmy Fernando'),
  ('EL5006', 'cflores@utec.edu.pe', 'Flores Vega, Christian Humberto'),
  ('EL5006', 'mlozano@utec.edu.pe', 'Lozano Bravo, Miguel Angel'),
  ('EL5006', 'mnunez@utec.edu.pe', 'Nuñez Ochoa, Moises'),
  ('EL5006', 'saranda@utec.edu.pe', 'Aranda Egusquiza, Sergio Rafael'),
  ('EL5102', 'aduenas@utec.edu.pe', 'Dueñas Rodriguez, Abel'),
  ('EL5102', 'jtarrillo@utec.edu.pe', 'Tarrillo Olano, Jimmy Fernando'),
  ('EL5102', 'lvolodina@utec.edu.pe', 'Volodina Egorovna de Denegri,  Ludmila'),
  ('EL5102', 'saranda@utec.edu.pe', 'Aranda Egusquiza, Sergio Rafael'),
  ('EL5302', 'mclemente@utec.edu.pe', 'Clemente Arenas, Mark Donny'),
  ('EL5303', 'conaka@utec.edu.pe', 'Onaka Nuñez, Carlos Henry'),
  ('EL5304', 'saranda@utec.edu.pe', 'Aranda Egusquiza, Sergio Rafael'),
  ('EL5305', 'cdiazp@utec.edu.pe', 'Diaz Pozzuoli, Carlos Francisco'),
  ('EL5305', 'spalomino@utec.edu.pe', 'Palomino Barzola, Styven (Asistente de enseñanza senior)'),
  ('EL5306', 'djara@utec.edu.pe', 'Jara Zumaran, Diego Marcos'),
  ('EL5306', 'lcastillo@utec.edu.pe', 'Castillo Campos, Luis Roberto'),
  ('EL5307', 'framirez@utec.edu.pe', 'Ramirez Horna, Flavio Cesar'),
  ('EL5308', 'gmichhue@utec.edu.pe', 'Michhue Vela, Gabriel Percy'),
  ('EL5309', 'jlezama@utec.edu.pe', 'Lezama Calvo, Jinmi'),
  ('EL5309', 'mclemente@utec.edu.pe', 'Clemente Arenas, Mark Donny'),
  ('EL5311', 'conaka@utec.edu.pe', 'Onaka Nuñez, Carlos Henry'),
  ('EL5311', 'mnunez@utec.edu.pe', 'Nuñez Ochoa, Moises'),
  ('EL5312', 'smorales@utec.edu.pe', 'Morales Azañedo, Sergio'),
  ('EL5313', 'pcrisostomo@utec.edu.pe', 'Crisostomo Romero, Pedro Moises'),
  ('EL5319', 'framirez@utec.edu.pe', 'Ramirez Horna, Flavio Cesar'),
  ('EL6011', 'fcamacho@utec.edu.pe', 'Camacho Jiménez, Francisco José'),
  ('EL6011', 'mlozano@utec.edu.pe', 'Lozano Bravo, Miguel Angel'),
  ('EN2011', 'rvera@utec.edu.pe', 'Vera Pomalaza, Rafael Ivan'),
  ('EN2013', 'rescudero@utec.edu.pe', 'Escudero Rodriguez, Ricardo Rolando'),
  ('EN2014', 'paraujo@utec.edu.pe', 'Araujo Pantoja, Patricia'),
  ('EN3011', 'rescudero@utec.edu.pe', 'Escudero Rodriguez, Ricardo Rolando'),
  ('EN3012', 'rescudero@utec.edu.pe', 'Escudero Rodriguez, Ricardo Rolando'),
  ('EN3013', 'jmaravi@utec.edu.pe', 'Maravi Camargo, Jesus Edgar'),
  ('EN3014', 'wramosv@utec.edu.pe', 'Ramos Vasquez, Williams Javier'),
  ('EN3015', 'rescudero@utec.edu.pe', 'Escudero Rodriguez, Ricardo Rolando'),
  ('EN3016', 'jramos@utec.edu.pe', 'Ramos Saravia, José César'),
  ('EN3017', 'vnunez@utec.edu.pe', 'Nuñez Ciallella, Virginia  Julieta'),
  ('EN3018', 'eramirez@utec.edu.pe', 'Ramirez Quiroz, Elmer Hernán'),
  ('EN4011', 'eramirez@utec.edu.pe', 'Ramirez Quiroz, Elmer Hernán'),
  ('EN4012', 'jmaravi@utec.edu.pe', 'Maravi Camargo, Jesus Edgar'),
  ('EN4013', 'lpinto@utec.edu.pe', 'Pinto Cieza, Lucila'),
  ('EN4014', 'dvilcat@utec.edu.pe', 'Vilca Tomaylla, David'),
  ('EN5004', 'jramos@utec.edu.pe', 'Ramos Saravia, José César'),
  ('EN5004', 'rescudero@utec.edu.pe', 'Escudero Rodriguez, Ricardo Rolando'),
  ('EN5004', 'rvera@utec.edu.pe', 'Vera Pomalaza, Rafael Ivan'),
  ('EN5101', 'eramirez@utec.edu.pe', 'Ramirez Quiroz, Elmer Hernán'),
  ('EN5101', 'paraujo@utec.edu.pe', 'Araujo Pantoja, Patricia'),
  ('EN5101', 'rvera@utec.edu.pe', 'Vera Pomalaza, Rafael Ivan'),
  ('EN5302', 'rvera@utec.edu.pe', 'Vera Pomalaza, Rafael Ivan'),
  ('EN5303', 'rvera@utec.edu.pe', 'Vera Pomalaza, Rafael Ivan'),
  ('EN5304', 'rliy@utec.edu.pe', 'Liy Lion, Roger Daniel'),
  ('EN5305', 'rliy@utec.edu.pe', 'Liy Lion, Roger Daniel'),
  ('EN5306', 'paraujo@utec.edu.pe', 'Araujo Pantoja, Patricia'),
  ('EN5307', 'jramos@utec.edu.pe', 'Ramos Saravia, José César'),
  ('EN5309', 'rliy@utec.edu.pe', 'Liy Lion, Roger Daniel'),
  ('EN5401', 'xguardia@utec.edu.pe', 'Guardia Muguruza, Ximena'),
  ('EN5403', 'lpinto@utec.edu.pe', 'Pinto Cieza, Lucila'),
  ('EN5404', 'jmaravi@utec.edu.pe', 'Maravi Camargo, Jesus Edgar'),
  ('EN6101', 'jchiroque@utec.edu.pe', 'Chiroque Calderon, Jorge Luis'),
  ('GH0023', 'kneira@utec.edu.pe', 'Neira Neira, Kenny'),
  ('GI2101', 'cguevara@utec.edu.pe', 'Guevara Medina, Carlos Cesar'),
  ('GI2101', 'jvalencia@utec.edu.pe', 'Valencia Zapata, Julian'),
  ('GI2101', 'rcondorena@utec.edu.pe', 'Condorena Franco, Rodolfo del Carmen'),
  ('GI2101', 'ycentty@utec.edu.pe', 'Centty Gutierrez, Yessica Maria'),
  ('GI3101', 'jcastillor@utec.edu.pe', 'Castillo Ramirez, Jose Winston'),
  ('GI3101', 'jsanchez@utec.edu.pe', 'Sanchez Paredes, Juan Magno'),
  ('GI3101', 'lobispo@utec.edu.pe', 'Obispo Sotomayor, Lester Alberto'),
  ('GI3101', 'marauco@utec.edu.pe', 'Arauco Loyola, Mario Enrique'),
  ('GI3101', 'mvelasquez@utec.edu.pe', 'Velasquez Alva, Miguel Angel'),
  ('GI3201', 'cgutierrezz@utec.edu.pe', 'Gutierrez Zevallos, Cristian'),
  ('GI4101', 'cgutierrezz@utec.edu.pe', 'Gutierrez Zevallos, Cristian'),
  ('GI4101', 'dramirez@utec.edu.pe', 'Ramirez Fonseca, Diana Estefania'),
  ('GI4101', 'jaguilar@utec.edu.pe', 'Aguilar Alfaro, José Manuel'),
  ('GI4101', 'jcastillor@utec.edu.pe', 'Castillo Ramirez, Jose Winston'),
  ('GI4101', 'jespinozam@utec.edu.pe', 'Espinoza Matos, José Francisco'),
  ('GI4101', 'jsanchez@utec.edu.pe', 'Sanchez Paredes, Juan Magno'),
  ('GI4101', 'mvelasquez@utec.edu.pe', 'Velasquez Alva, Miguel Angel'),
  ('GI5101', 'aestrada@utec.edu.pe', 'Estrada Merino, Alfredo'),
  ('GI5101', 'exicota@utec.edu.pe', 'XICOTA TORRES, ESTER'),
  ('GI5101', 'jespinozam@utec.edu.pe', 'Espinoza Matos, José Francisco'),
  ('GI5101', 'jherran@utec.edu.pe', 'Herrán Arias, José Luis'),
  ('GI5101', 'jramirezb@utec.edu.pe', 'Ramirez Bohada, Juan Carlos'),
  ('GI5101', 'jvalencia@utec.edu.pe', 'Valencia Zapata, Julian'),
  ('GI5101', 'mtoro@utec.edu.pe', 'Toro Galeno, Manuel Leonardo'),
  ('GI5101', 'ovento@utec.edu.pe', 'Vento Garcia, Oscar Arturo'),
  ('HH2101', 'aescudero@utec.edu.pe', 'Escudero Villanueva, Alfredo Luis'),
  ('HH2101', 'anunezd@utec.edu.pe', 'Nuñez Del Prado Tavara, Aaron'),
  ('HH2101', 'ebaca@utec.edu.pe', 'Baca Marroquin, Emily'),
  ('HH2101', 'gespinozad@utec.edu.pe', 'Espinoza Delgado, Giancarlo'),
  ('HH2101', 'jpino@utec.edu.pe', 'Pino Matos, Jose'),
  ('HH2101', 'mstiglich@utec.edu.pe', 'Stiglich Labarthe, Matteo'),
  ('HH2102', 'anunezd@utec.edu.pe', 'Nuñez Del Prado Tavara, Aaron'),
  ('HH2102', 'gespinozad@utec.edu.pe', 'Espinoza Delgado, Giancarlo'),
  ('HH2102', 'kchuspe@utec.edu.pe', 'Chuspe Apaza, Keyko Gladys'),
  ('HH2102', 'lsanchezp@utec.edu.pe', 'Sanchez Perez, Luz de los Angeles'),
  ('HH2102', 'nbonopaladino@utec.edu.pe', 'Bonopaladino Obando, Nubia Elena'),
  ('HH2201', 'cmarquez@utec.edu.pe', 'Marquez Abad, Carla Alejandra'),
  ('HH2202', 'galexandrino@utec.edu.pe', 'Alexandrino Ocaña, Grace Eliana'),
  ('HH2204', 'csagastegui@utec.edu.pe', 'Sagastegui Heredia, Carla Liliana'),
  ('HH2205', 'adelaflor@utec.edu.pe', 'De La Flor Basterrechea, Antuané'),
  ('HH2206', 'cmarquez@utec.edu.pe', 'Marquez Abad, Carla Alejandra'),
  ('HH2207', 'vramirez@utec.edu.pe', 'Ramirez Herrera, Victor Gonzalo'),
  ('HH3101', 'adelaflor@utec.edu.pe', 'De La Flor Basterrechea, Antuané'),
  ('HH3101', 'ahopkins@utec.edu.pe', 'Hopkins Barriga, Aranzazu Marcela'),
  ('HH3101', 'calayza@utec.edu.pe', 'Alayza Prager, Cristina'),
  ('HH3101', 'dcastillo@utec.edu.pe', 'Castillo Cerf, Diana'),
  ('HH3101', 'ggarcia@utec.edu.pe', 'Garcia Benavente, Gabriela'),
  ('HH3101', 'icollazos@utec.edu.pe', 'Collazos Ticona, Isabel del Carmen'),
  ('HH3201', 'cmarquez@utec.edu.pe', 'Marquez Abad, Carla Alejandra'),
  ('HH4201', 'acalderon@utec.edu.pe', 'Calderon Prada, Alicia'),
  ('HH4203', 'ohidalgo@utec.edu.pe', 'Hidalgo Wuest, Oscar'),
  ('HH5001', 'exicota@utec.edu.pe', 'XICOTA TORRES, ESTER'),
  ('HH5101', 'amillan@utec.edu.pe', 'Millán Falconí, Armando'),
  ('HH5101', 'calayza@utec.edu.pe', 'Alayza Prager, Cristina'),
  ('HH5101', 'ddavila@utec.edu.pe', 'Davila Morey, Dante'),
  ('HH5101', 'jarana@utec.edu.pe', 'Arana Alencastre, Jean Luis'),
  ('HH5101', 'roliart@utec.edu.pe', 'Oliart Bonilla, Rodrigo Nicolas'),
  ('HH6001', 'ccabezas@utec.edu.pe', 'Cabezas Palacios, Claudia Teresa'),
  ('HH6001', 'czorrilla@utec.edu.pe', 'Zorrilla Aranguren, Carlos Marcelo'),
  ('HH6001', 'dcespedesc@utec.edu.pe', 'Cespedes Cano, Daniel'),
  ('HH6001', 'dgonzales@utec.edu.pe', 'Gonzales Camacho, Daniel Isaac'),
  ('HH6001', 'gacosta@utec.edu.pe', 'Acosta Pelaez, Gonzalo'),
  ('HH6001', 'jmunoz@utec.edu.pe', 'Muñoz Rios, Jimena Sol'),
  ('HH6001', 'ohidalgo@utec.edu.pe', 'Hidalgo Wuest, Oscar'),
  ('HH6001', 'treyes@utec.edu.pe', 'Reyes Arcos, Tania Belen'),
  ('HH6001', 'vramirez@utec.edu.pe', 'Ramirez Herrera, Victor Gonzalo'),
  ('HH6002', 'gacosta@utec.edu.pe', 'Acosta Pelaez, Gonzalo'),
  ('HH6002', 'ohidalgo@utec.edu.pe', 'Hidalgo Wuest, Oscar'),
  ('HH6002', 'treyes@utec.edu.pe', 'Reyes Arcos, Tania Belen'),
  ('HH6002', 'vcaballero@utec.edu.pe', 'Caballero Reynoso, Veronica'),
  ('HH6002', 'vramirez@utec.edu.pe', 'Ramirez Herrera, Victor Gonzalo'),
  ('IN2003', 'fcornillier@utec.edu.pe', 'Cornillier, Fabien Yves Paul'),
  ('IN2003', 'lfloresl@utec.edu.pe', 'Flores Luyo, Luis Ernesto'),
  ('IN2004', 'jdelapuente@utec.edu.pe', 'De La Puente Maldonado, Jose Gaspar'),
  ('IN2004', 'ocanasas@utec.edu.pe', 'Canasas Gil, Oswaldo Manuel'),
  ('IN2005', 'cantonini@utec.edu.pe', 'Antonini Bova, Claudia Fausta Maura'),
  ('IN2005', 'ogalarza@utec.edu.pe', 'Galarza Geronimo, Orlando Alfredo'),
  ('IN3003', 'cnunura@utec.edu.pe', 'Nunura Nunura, Cesar Rolando'),
  ('IN3003', 'fcamacho@utec.edu.pe', 'Camacho Jiménez, Francisco José'),
  ('IN3004', 'uvelazco@utec.edu.pe', 'Velazco Cespedez, Ursula Angelica'),
  ('IN3005', 'fcornillier@utec.edu.pe', 'Cornillier, Fabien Yves Paul'),
  ('IN3006', 'qmeza@utec.edu.pe', 'Meza Huallpa, Quemer Luis'),
  ('IN3007', 'ggonzales@utec.edu.pe', 'Gonzalez Carpio, George Jessus'),
  ('IN3007', 'qmeza@utec.edu.pe', 'Meza Huallpa, Quemer Luis'),
  ('IN3008', 'ogamonal@utec.edu.pe', 'Gamonal Pajares, Oscar Pablo'),
  ('IN3009', 'jbueno@utec.edu.pe', 'Bueno Villanueva, Juan Carlos'),
  ('IN3010', 'jbueno@utec.edu.pe', 'Bueno Villanueva, Juan Carlos'),
  ('IN3011', 'cantonini@utec.edu.pe', 'Antonini Bova, Claudia Fausta Maura'),
  ('IN3012', 'ggonzales@utec.edu.pe', 'Gonzalez Carpio, George Jessus'),
  ('IN3012', 'ogamonal@utec.edu.pe', 'Gamonal Pajares, Oscar Pablo'),
  ('IN4007', 'jgranadoso@utec.edu.pe', 'Granados Ore, Jose Carlos'),
  ('IN4007', 'qmeza@utec.edu.pe', 'Meza Huallpa, Quemer Luis'),
  ('IN4008', 'jcerda@utec.edu.pe', 'CERDA HERNANDEZ, JOSE JAVIER'),
  ('IN4009', 'clegua@utec.edu.pe', 'Legua Perez, Carlos Rolando'),
  ('IN4301', 'dhernandezs@utec.edu.pe', 'Hernandez Saldaña, Dario Irving'),
  ('IN4302', 'lrodriguezw@utec.edu.pe', 'Rodriguez Wu, Lucia Geovanna'),
  ('IN4304', 'cramirezl@utec.edu.pe', 'Ramirez Luna, Christian'),
  ('IN4305', 'ogamonal@utec.edu.pe', 'Gamonal Pajares, Oscar Pablo'),
  ('IN5007', 'lfloresl@utec.edu.pe', 'Flores Luyo, Luis Ernesto'),
  ('IN5008', 'sarevalo@utec.edu.pe', 'Arevalo Ventocilla, Silvanna'),
  ('IN5011', 'cantonini@utec.edu.pe', 'Antonini Bova, Claudia Fausta Maura'),
  ('IN5011', 'gpella@utec.edu.pe', 'Pella Fernandez, Gabriela'),
  ('IN5011', 'jbueno@utec.edu.pe', 'Bueno Villanueva, Juan Carlos'),
  ('IN5011', 'jdelapuente@utec.edu.pe', 'De La Puente Maldonado, Jose Gaspar'),
  ('IN5011', 'jugarte@utec.edu.pe', 'Ugarte Chamorro, Jose Luis'),
  ('IN5011', 'lfloresl@utec.edu.pe', 'Flores Luyo, Luis Ernesto'),
  ('IN5107', 'ggonzales@utec.edu.pe', 'Gonzalez Carpio, George Jessus'),
  ('IN5107', 'gpella@utec.edu.pe', 'Pella Fernandez, Gabriela'),
  ('IN5107', 'jdelapuente@utec.edu.pe', 'De La Puente Maldonado, Jose Gaspar'),
  ('IN5107', 'jinga@utec.edu.pe', 'Inga Samaniego, Jean Carlos'),
  ('IN5107', 'jugarte@utec.edu.pe', 'Ugarte Chamorro, Jose Luis'),
  ('IN5107', 'lvolodina@utec.edu.pe', 'Volodina Egorovna de Denegri,  Ludmila'),
  ('IN5301', 'vzuniga@utec.edu.pe', 'Zuñiga Guerrero, Vicente Mohamed'),
  ('IN5302', 'jarteagacu@utec.edu.pe', 'ARTEAGA CUEVA, JAVIER ALCIDES'),
  ('IN5304', 'lgomez@utec.edu.pe', 'Gomez Bustamante, Luis'),
  ('IN5306', 'jvillavicencio@utec.edu.pe', 'Villavicencio Antunez, Jorge'),
  ('IN5309', 'gpella@utec.edu.pe', 'Pella Fernandez, Gabriela'),
  ('IN5310', 'ggonzales@utec.edu.pe', 'Gonzalez Carpio, George Jessus'),
  ('IN6011', 'qmeza@utec.edu.pe', 'Meza Huallpa, Quemer Luis'),
  ('IN6012', 'ogamonal@utec.edu.pe', 'Gamonal Pajares, Oscar Pablo'),
  ('IN6012', 'qmeza@utec.edu.pe', 'Meza Huallpa, Quemer Luis'),
  ('IQ2001', 'aflores@utec.edu.pe', 'Flores Lima, Artemio'),
  ('IQ2001', 'echavez@utec.edu.pe', 'Chavez Gonzales, Erika'),
  ('IQ2002', 'cfloresb@utec.edu.pe', 'Flores Barreda, Carmen Elena'),
  ('IQ2003', 'ftarazona@utec.edu.pe', 'Tarazona Vasquez, Francisco'),
  ('IQ2003', 'wramosv@utec.edu.pe', 'Ramos Vasquez, Williams Javier'),
  ('IQ3001', 'mchuman@utec.edu.pe', 'Chuman Lopez, Margeo Javier'),
  ('IQ3002', 'wramosv@utec.edu.pe', 'Ramos Vasquez, Williams Javier'),
  ('IQ3003', 'dparada@utec.edu.pe', 'Parada Quinaya, Diana Carolina'),
  ('IQ3003', 'mchuman@utec.edu.pe', 'Chuman Lopez, Margeo Javier'),
  ('IQ3004', 'azuniga@utec.edu.pe', 'Zuñiga Tunque, Americo'),
  ('IQ3004', 'mcarranza@utec.edu.pe', 'Carranza Oropeza, Maria Veronica'),
  ('IQ3005', 'lvargas@utec.edu.pe', 'Vargas Figueroa, Luis Cesar'),
  ('IQ3006', 'kgonzales@utec.edu.pe', 'Gonzales Rojas, Karen'),
  ('IQ3006', 'mchuman@utec.edu.pe', 'Chuman Lopez, Margeo Javier'),
  ('IQ4001', 'aflores@utec.edu.pe', 'Flores Lima, Artemio'),
  ('IQ4002', 'vfigueroa@utec.edu.pe', 'Figueroa Jachilla, Vanessa'),
  ('IQ4003', 'jbanon@utec.edu.pe', 'Bañon Arias, Jonnatan Victor'),
  ('IQ4003', 'mcarranza@utec.edu.pe', 'Carranza Oropeza, Maria Veronica'),
  ('IQ4004', 'gmamani@utec.edu.pe', 'Mamani Paco, Giussepi Ali Jhonatan'),
  ('IQ4222', 'jguerrero@utec.edu.pe', 'Guerrero Guevara, Jose Luis'),
  ('IQ4222', 'vfigueroa@utec.edu.pe', 'Figueroa Jachilla, Vanessa'),
  ('IQ5001', 'ccaceres@utec.edu.pe', 'Cáceres Mendoza, Cayetano Juan'),
  ('IQ5001', 'jbanon@utec.edu.pe', 'Bañon Arias, Jonnatan Victor'),
  ('IQ5002', 'aflores@utec.edu.pe', 'Flores Lima, Artemio'),
  ('IQ5003', 'etejada@utec.edu.pe', 'TEJADA GUTIERREZ, EBERTH SANDRO'),
  ('IQ5333', 'hames@utec.edu.pe', 'Ames Ramirez, Huguez Enrique'),
  ('IQ5333', 'uquiroz@utec.edu.pe', 'QUIROZ AGUINAGA, ULISES'),
  ('IQ5334', 'vmadrid@utec.edu.pe', 'Madrid Brañes, Vianca Vanessa'),
  ('IQ5335', 'azuniga@utec.edu.pe', 'Zuñiga Tunque, Americo'),
  ('IQ5335', 'nlopez@utec.edu.pe', 'Lopez Rodriguez, Naudy Ricardo'),
  ('IQ5336', 'jguerrero@utec.edu.pe', 'Guerrero Guevara, Jose Luis'),
  ('IQ6001', 'lvargas@utec.edu.pe', 'Vargas Figueroa, Luis Cesar'),
  ('IQ6002', 'aflores@utec.edu.pe', 'Flores Lima, Artemio'),
  ('IQ6002', 'echavez@utec.edu.pe', 'Chavez Gonzales, Erika'),
  ('IS2011', 'dchira@utec.edu.pe', 'Chira Siaden, David Gustavo'),
  ('IS2021', 'ladanaque@utec.edu.pe', 'Adanaque Infante, Luz Antuanet'),
  ('IS3012', 'kcelis@utec.edu.pe', 'Celis Osores, Karla Soledad'),
  ('IS4024', 'wjulca@utec.edu.pe', 'JULCA MEJIA, WILSON'),
  ('IS5201', 'kruiz@utec.edu.pe', 'RUIZ KUAN, KAT LIM'),
  ('IS5202', 'acardenasm@utec.edu.pe', 'Cardenas Maita, Ana Rocio'),
  ('IS5203', 'ctenorio@utec.edu.pe', 'TENORIO GONZALES, CANDY VERONICA'),
  ('IS5205', 'acardenasm@utec.edu.pe', 'Cardenas Maita, Ana Rocio'),
  ('IS6001', 'ctenorio@utec.edu.pe', 'TENORIO GONZALES, CANDY VERONICA'),
  ('ME2012', 'scandiotti@utec.edu.pe', 'Candiotti Barrenechea, Sergio Alonso'),
  ('ME2013', 'scandiotti@utec.edu.pe', 'Candiotti Barrenechea, Sergio Alonso'),
  ('ME2013', 'vorihuela@utec.edu.pe', 'Orihuela Munive, Vanessa'),
  ('ME2014', 'scandiotti@utec.edu.pe', 'Candiotti Barrenechea, Sergio Alonso'),
  ('ME3011', 'jmendozam@utec.edu.pe', 'Mendoza Montalvo, Jimmy'),
  ('ME3012', 'aperalta@utec.edu.pe', 'Peralta Serrano, Alexander'),
  ('ME3012', 'scharca@utec.edu.pe', 'Charca Mamani, Samuel'),
  ('ME3013', 'cnunura@utec.edu.pe', 'Nunura Nunura, Cesar Rolando'),
  ('ME3014', 'eramirez@utec.edu.pe', 'Ramirez Quiroz, Elmer Hernán'),
  ('ME3015', 'halvarez@utec.edu.pe', 'Alvarez Sanchez, Helard Henry'),
  ('ME3016', 'jsanchezs@utec.edu.pe', 'Sanchez Sandoval, Juan'),
  ('ME3017', 'vorihuela@utec.edu.pe', 'Orihuela Munive, Vanessa'),
  ('ME4011', 'jsanchezs@utec.edu.pe', 'Sanchez Sandoval, Juan'),
  ('ME5007', 'halvarez@utec.edu.pe', 'Alvarez Sanchez, Helard Henry'),
  ('ME5007', 'jguerrero@utec.edu.pe', 'Guerrero Guevara, Jose Luis'),
  ('ME5007', 'obejarano@utec.edu.pe', 'Bejarano Grandez, Omar'),
  ('ME5007', 'scharca@utec.edu.pe', 'Charca Mamani, Samuel'),
  ('ME5007', 'vorihuela@utec.edu.pe', 'Orihuela Munive, Vanessa'),
  ('ME5104', 'halvarez@utec.edu.pe', 'Alvarez Sanchez, Helard Henry'),
  ('ME5104', 'mwdkim@utec.edu.pe', 'Kim, Wangdo'),
  ('ME5104', 'obejarano@utec.edu.pe', 'Bejarano Grandez, Omar'),
  ('ME5104', 'paraujo@utec.edu.pe', 'Araujo Pantoja, Patricia'),
  ('ME5104', 'vorihuela@utec.edu.pe', 'Orihuela Munive, Vanessa'),
  ('ME5301', 'jguerrero@utec.edu.pe', 'Guerrero Guevara, Jose Luis'),
  ('ME5302', 'japaza@utec.edu.pe', 'Apaza Nina, Jose Enrique'),
  ('ME5303', 'japaza@utec.edu.pe', 'Apaza Nina, Jose Enrique'),
  ('ME5304', 'vorihuela@utec.edu.pe', 'Orihuela Munive, Vanessa'),
  ('ME5305', 'lhurtadoc@utec.edu.pe', 'Hurtado Campos, Luis'),
  ('ME5306', 'lhurtadoc@utec.edu.pe', 'Hurtado Campos, Luis'),
  ('ME5307', 'cnunura@utec.edu.pe', 'Nunura Nunura, Cesar Rolando'),
  ('ME5308', 'halvarez@utec.edu.pe', 'Alvarez Sanchez, Helard Henry'),
  ('ME5310', 'cnunura@utec.edu.pe', 'Nunura Nunura, Cesar Rolando'),
  ('ME5312', 'mwdkim@utec.edu.pe', 'Kim, Wangdo'),
  ('ME5313', 'mwdkim@utec.edu.pe', 'Kim, Wangdo'),
  ('ME5314', 'mwdkim@utec.edu.pe', 'Kim, Wangdo'),
  ('ME5402', 'jguerrero@utec.edu.pe', 'Guerrero Guevara, Jose Luis'),
  ('ME6101', 'volivera@utec.edu.pe', 'Olivera Oliva, Davy Alonso'),
  ('ME6102', 'jmorales@utec.edu.pe', 'Morales Ortiz, Jorge Arturo'),
  ('ME6102', 'volivera@utec.edu.pe', 'Olivera Oliva, Davy Alonso'),
  ('MT2001', 'jbohorquez@utec.edu.pe', 'Bohorquez Bendezu, Jose Luis'),
  ('MT2001', 'wbarrutia@utec.edu.pe', 'Barrutia Alta, Walter Sebastian'),
  ('MT3001', 'lgarciaz@utec.edu.pe', 'Garcia Zevallos, Luis Enrique'),
  ('MT3001', 'rmiranda@utec.edu.pe', 'Miranda Barrueto, Renato Alonso'),
  ('MT3001', 'spalomino@utec.edu.pe', 'Palomino Barzola, Styven (Asistente de enseñanza senior)'),
  ('MT4001', 'jcallupe@utec.edu.pe', 'Callupe Luna, Jhedmar Jhonatan'),
  ('MT4001', 'jlopezm@utec.edu.pe', 'Lopez Manrique, Jose Alexander'),
  ('MT4002', 'rcabrerad@utec.edu.pe', 'Cabrera Donayre, Rony Martin'),
  ('MT4002', 'rmiranda@utec.edu.pe', 'Miranda Barrueto, Renato Alonso'),
  ('MT4002', 'spalomino@utec.edu.pe', 'Palomino Barzola, Styven (Asistente de enseñanza senior)'),
  ('MT4003', 'ejara@utec.edu.pe', 'Jara Alegria, Elvis Omar'),
  ('MT4003', 'pfloresa@utec.edu.pe', 'Flores Alvarez, Pedro alonso'),
  ('MT5001', 'ejara@utec.edu.pe', 'Jara Alegria, Elvis Omar'),
  ('MT5001', 'jmagallanesc@utec.edu.pe', 'MAGALLANES CARDENAS, JOSE RODRIGO'),
  ('MT5001', 'mpuchuri@utec.edu.pe', 'Puchuri Lopez, Marko'),
  ('MT5003', 'cflores@utec.edu.pe', 'Flores Vega, Christian Humberto'),
  ('MT5003', 'dhuamanchahua@utec.edu.pe', 'Huamanchahua Canchanya, Deyby'),
  ('MT5003', 'dinga@utec.edu.pe', 'Inga Narvaez, Dante'),
  ('MT5003', 'ejara@utec.edu.pe', 'Jara Alegria, Elvis Omar'),
  ('MT5003', 'jcallupe@utec.edu.pe', 'Callupe Luna, Jhedmar Jhonatan'),
  ('MT5003', 'jtapullima@utec.edu.pe', 'TAPULLIMA MONTEJO, JONATHAN ALFREDO'),
  ('MT5003', 'rcabrerad@utec.edu.pe', 'Cabrera Donayre, Rony Martin'),
  ('MT5003', 'wbarrutia@utec.edu.pe', 'Barrutia Alta, Walter Sebastian'),
  ('MT5103', 'dinga@utec.edu.pe', 'Inga Narvaez, Dante'),
  ('MT5103', 'iyupanqui@utec.edu.pe', 'Yupanqui Tello, Ivan Francisco'),
  ('MT5103', 'jtarrillo@utec.edu.pe', 'Tarrillo Olano, Jimmy Fernando'),
  ('MT5103', 'lvolodina@utec.edu.pe', 'Volodina Egorovna de Denegri,  Ludmila'),
  ('MT5103', 'rcabrerad@utec.edu.pe', 'Cabrera Donayre, Rony Martin'),
  ('MT5103', 'wbarrutia@utec.edu.pe', 'Barrutia Alta, Walter Sebastian'),
  ('MT5305', 'jlopezm@utec.edu.pe', 'Lopez Manrique, Jose Alexander'),
  ('MT5305', 'oramos@utec.edu.pe', 'Ramos Ponce, Oscar Efraín'),
  ('MT5306', 'lgarciaz@utec.edu.pe', 'Garcia Zevallos, Luis Enrique'),
  ('MT5306', 'rcabrerad@utec.edu.pe', 'Cabrera Donayre, Rony Martin'),
  ('MT5307', 'agutarra@utec.edu.pe', 'Gutarra Sanchez, Anthony Gerardo'),
  ('MT5307', 'iyupanqui@utec.edu.pe', 'Yupanqui Tello, Ivan Francisco'),
  ('MT5312', 'jfabianl@utec.edu.pe', 'Fabían Lizárraga, Joao Ulises'),
  ('MT5313', 'jtapullima@utec.edu.pe', 'TAPULLIMA MONTEJO, JONATHAN ALFREDO'),
  ('MT6011', 'molortegui@utec.edu.pe', 'Olortegui Huaman, Miguel Tomas'),
  ('MT6011', 'nrojas@utec.edu.pe', 'Rojas muñoz, Nimrod Angel'),
  ('MT6011', 'spalomino@utec.edu.pe', 'Palomino Barzola, Styven (Asistente de enseñanza senior)'),
  ('PI3103', 'aestrada@utec.edu.pe', 'Estrada Merino, Alfredo'),
  ('PI3103', 'cpereira@utec.edu.pe', 'Pereira Castro, Carlos Alberto'),
  ('PI3103', 'czorrilla@utec.edu.pe', 'Zorrilla Aranguren, Carlos Marcelo'),
  ('PI3103', 'gpella@utec.edu.pe', 'Pella Fernandez, Gabriela'),
  ('PI3103', 'jgonzales@utec.edu.pe', 'Gonzales Balladares, Julio'),
  ('PI3103', 'jmoranj@utec.edu.pe', 'Moran Jorquera, Jessica'),
  ('PI3103', 'jsanchez@utec.edu.pe', 'Sanchez Paredes, Juan Magno'),
  ('PI3103', 'jvelarde@utec.edu.pe', 'Velarde Espinoza, Jose'),
  ('PI3103', 'lvolodina@utec.edu.pe', 'Volodina Egorovna de Denegri,  Ludmila'),
  ('PI3103', 'szamora@utec.edu.pe', 'ZAMORA ESTRADA, SILVANA CONSUELO'),
  ('PI3103', 'vfreundt@utec.edu.pe', 'Freundt Melendez, Victor Gustavo'),
  ('PI6001', 'adelaflor@utec.edu.pe', 'De La Flor Basterrechea, Antuané'),
  ('PI6001', 'adeleo@utec.edu.pe', 'De Leo Martinez, Andrés'),
  ('PI6001', 'amackay@utec.edu.pe', 'Mac Kay Fulle, Arturo Martin'),
  ('PI6001', 'amillan@utec.edu.pe', 'Millán Falconí, Armando'),
  ('PI6001', 'ebaca@utec.edu.pe', 'Baca Marroquin, Emily'),
  ('PI6001', 'fburneo@utec.edu.pe', 'Burneo Velezmoro, Fiorella'),
  ('PI6001', 'galexandrino@utec.edu.pe', 'Alexandrino Ocaña, Grace Eliana'),
  ('PI6001', 'gespinozad@utec.edu.pe', 'Espinoza Delgado, Giancarlo'),
  ('PI6001', 'ggarcia@utec.edu.pe', 'Garcia Benavente, Gabriela'),
  ('PI6001', 'jmunoz@utec.edu.pe', 'Muñoz Rios, Jimena Sol'),
  ('PI6001', 'jpino@utec.edu.pe', 'Pino Matos, Jose'),
  ('PI6001', 'mdelcastillo@utec.edu.pe', 'del Castillo Tafur, Mary Cynthia'),
  ('PI6001', 'mstiglich@utec.edu.pe', 'Stiglich Labarthe, Matteo'),
  ('PI6001', 'smontoya@utec.edu.pe', 'Montoya Alarcon De Hamoir, Sheyla Rosa'),
  ('PI6002', 'earellanos@utec.edu.pe', 'Arellanos Tafur, Elmer Hugo'),
  ('PI6002', 'fcastillo@utec.edu.pe', 'Castillo Castillo, Fabrizio Julio'),
  ('PI6002', 'jbohorquez@utec.edu.pe', 'Bohorquez Bendezu, Jose Luis'),
  ('PI6002', 'jpaucara@utec.edu.pe', 'Paucara Prado, Jhonatan David'),
  ('PI6002', 'jvelarde@utec.edu.pe', 'Velarde Espinoza, Jose'),
  ('PI6002', 'nrojas@utec.edu.pe', 'Rojas muñoz, Nimrod Angel'),
  ('PI6002', 'oortiz@utec.edu.pe', 'Ortiz Cabello, Omar Hernan'),
  ('PI6002', 'rtorresa@utec.edu.pe', 'Torres Aragon, Ricardo'),
  ('QI5010', 'urodriguez@utec.edu.pe', 'Rodriguez Zuñiga, Ursula Fabiola'),
  ('QI5109', 'aflores@utec.edu.pe', 'Flores Lima, Artemio'),
  ('QI5109', 'etejada@utec.edu.pe', 'TEJADA GUTIERREZ, EBERTH SANDRO'),
  ('QI5109', 'mcarranza@utec.edu.pe', 'Carranza Oropeza, Maria Veronica')
on conflict (course_code, teacher_email) do update
  set teacher_name = excluded.teacher_name,
      is_current   = true;

-- Lo que salió se apaga sin borrarse: las FK de reviews siguen vivas.
update public.course_teachers
set is_current = false
where is_current
  and (course_code, teacher_email) not in (
    ('AD2003', 'mlunga@utec.edu.pe'),
    ('AD2007', 'ikalinowski@utec.edu.pe'),
    ('AD2008', 'jaguilar@utec.edu.pe'),
    ('AD2009', 'pperezq@utec.edu.pe'),
    ('AD2011', 'exicota@utec.edu.pe'),
    ('AD3001', 'jaguilar@utec.edu.pe'),
    ('AD3002', 'rcondorena@utec.edu.pe'),
    ('AD3003', 'mlunga@utec.edu.pe'),
    ('AD3004', 'lsalazar@utec.edu.pe'),
    ('AD3005', 'fcastillo@utec.edu.pe'),
    ('AD3006', 'lgomez@utec.edu.pe'),
    ('AD3010', 'amorantep@utec.edu.pe'),
    ('AD3014', 'dramirez@utec.edu.pe'),
    ('AD3015', 'smontoya@utec.edu.pe'),
    ('AD3017', 'sarevalo@utec.edu.pe'),
    ('AD3018', 'gvargas@utec.edu.pe'),
    ('AD3108', 'sotero@utec.edu.pe'),
    ('AD4001', 'aestrada@utec.edu.pe'),
    ('AD4002', 'zgallegos@utec.edu.pe'),
    ('AD4003', 'iorbegoso@utec.edu.pe'),
    ('AD4004', 'anue@utec.edu.pe'),
    ('AD4016', 'arojasd@utec.edu.pe'),
    ('AD4301', 'flache@utec.edu.pe'),
    ('AD4305', 'jaguilar@utec.edu.pe'),
    ('AD4307', 'kneira@utec.edu.pe'),
    ('AD4403', 'kneira@utec.edu.pe'),
    ('AD5001', 'kneira@utec.edu.pe'),
    ('AD5002', 'owong@utec.edu.pe'),
    ('AD5003', 'kgranda@utec.edu.pe'),
    ('AD5004', 'sarevalo@utec.edu.pe'),
    ('AD5018', 'amorantep@utec.edu.pe'),
    ('AD5019', 'cmarquezm@utec.edu.pe'),
    ('AD5114', 'ttijero@utec.edu.pe'),
    ('AD6001', 'ehernandez@utec.edu.pe'),
    ('AD6002', 'lobispo@utec.edu.pe'),
    ('AD6003', 'dluna@utec.edu.pe'),
    ('AD6005', 'ikalinowski@utec.edu.pe'),
    ('AD6006', 'mlunga@utec.edu.pe'),
    ('AD6007', 'lobispo@utec.edu.pe'),
    ('AD6032', 'kneira@utec.edu.pe'),
    ('AD6100', 'fvilela@utec.edu.pe'),
    ('AD6100', 'jvalencia@utec.edu.pe'),
    ('AD6100', 'kneira@utec.edu.pe'),
    ('AM1003', 'mlatorre@utec.edu.pe'),
    ('AM2001', 'mfloresf@utec.edu.pe'),
    ('AM2003', 'evereau@utec.edu.pe'),
    ('AM2003', 'rguerra@utec.edu.pe'),
    ('AM2004', 'cmillan@utec.edu.pe'),
    ('AM3001', 'hllauca@utec.edu.pe'),
    ('AM3001', 'kdelgado@utec.edu.pe'),
    ('AM3002', 'jmendozam@utec.edu.pe'),
    ('AM3003', 'irabitsch@utec.edu.pe'),
    ('AM3005', 'mporlles@utec.edu.pe'),
    ('AM3006', 'kdelgado@utec.edu.pe'),
    ('AM3007', 'lchuquisengo@utec.edu.pe'),
    ('AM4002', 'ahijar@utec.edu.pe'),
    ('AM4003', 'mriverac@utec.edu.pe'),
    ('AM4301', 'mlatorre@utec.edu.pe'),
    ('AM4302', 'imontes@utec.edu.pe'),
    ('AM4303', 'mriverac@utec.edu.pe'),
    ('AM4304', 'rguerra@utec.edu.pe'),
    ('AM4305', 'acongrains@utec.edu.pe'),
    ('AM4308', 'gmonge@utec.edu.pe'),
    ('AM4311', 'schero@utec.edu.pe'),
    ('AM4314', 'cmillan@utec.edu.pe'),
    ('AM4315', 'jzevallosr@utec.edu.pe'),
    ('AM5001', 'kdelgado@utec.edu.pe'),
    ('AM5002', 'janicama@utec.edu.pe'),
    ('AM5007', 'kdelgado@utec.edu.pe'),
    ('AM5106', 'kdelgado@utec.edu.pe'),
    ('AM5106', 'mriverac@utec.edu.pe'),
    ('AM6101', 'kdelgado@utec.edu.pe'),
    ('AM6102', 'mfloresf@utec.edu.pe'),
    ('AM6103', 'evereau@utec.edu.pe'),
    ('BA6001', 'jsaldana@utec.edu.pe'),
    ('BI1002', 'mcueva@utec.edu.pe'),
    ('BI2004', 'jbanon@utec.edu.pe'),
    ('BI3005', 'hsaavedra@utec.edu.pe'),
    ('BI3005', 'jhuacachi@utec.edu.pe'),
    ('BI3006', 'mcueva@utec.edu.pe'),
    ('BI3007', 'cfranco@utec.edu.pe'),
    ('BI3008', 'aagapito@utec.edu.pe'),
    ('BI3009', 'aariasm@utec.edu.pe'),
    ('BI3009', 'acordovar@utec.edu.pe'),
    ('BI3010', 'mcueva@utec.edu.pe'),
    ('BI4011', 'aquispeg@utec.edu.pe'),
    ('BI4012', 'pcardenas@utec.edu.pe'),
    ('BI4012', 'tcajahuanca@utec.edu.pe'),
    ('BI4013', 'ljaramillo@utec.edu.pe'),
    ('BI4014', 'hmanriquec@utec.edu.pe'),
    ('BI4430', 'acollantes@utec.edu.pe'),
    ('BI4431', 'jvaldivias@utec.edu.pe'),
    ('BI4432', 'acollantes@utec.edu.pe'),
    ('BI4433', 'ljaramillo@utec.edu.pe'),
    ('BI4434', 'mcueva@utec.edu.pe'),
    ('BI4435', 'gsandoval@utec.edu.pe'),
    ('BI4439', 'aratti@utec.edu.pe'),
    ('BI4439', 'gtravi@utec.edu.pe'),
    ('BI5009', 'hsaavedra@utec.edu.pe'),
    ('BI5009', 'jlezama@utec.edu.pe'),
    ('BI5009', 'mclemente@utec.edu.pe'),
    ('BI5009', 'pcrisostomo@utec.edu.pe'),
    ('BI5015', 'mclemente@utec.edu.pe'),
    ('BI5016', 'adonayre@utec.edu.pe'),
    ('BI5016', 'jhuacachi@utec.edu.pe'),
    ('BI5108', 'aariasm@utec.edu.pe'),
    ('BI5108', 'jlezama@utec.edu.pe'),
    ('BI5108', 'pcardenas@utec.edu.pe'),
    ('BI5318', 'pcrisostomo@utec.edu.pe'),
    ('BI5319', 'sflores@utec.edu.pe'),
    ('BI5320', 'lgamarra@utec.edu.pe'),
    ('BI5321', 'jfranco@utec.edu.pe'),
    ('BI5322', 'jfranco@utec.edu.pe'),
    ('BI5323', 'acardenasr@utec.edu.pe'),
    ('BI5324', 'jbanon@utec.edu.pe'),
    ('BI5325', 'adonayre@utec.edu.pe'),
    ('BI5326', 'adonayre@utec.edu.pe'),
    ('BI5327', 'kgonzales@utec.edu.pe'),
    ('BI5328', 'lperez@utec.edu.pe'),
    ('BI6001', 'mcueva@utec.edu.pe'),
    ('BI6002', 'mcueva@utec.edu.pe'),
    ('BI6003', 'cfranco@utec.edu.pe'),
    ('CC1101', 'crojas@utec.edu.pe'),
    ('CC1101', 'preynoso@utec.edu.pe'),
    ('CC1101', 'volivera@utec.edu.pe'),
    ('CC1102', 'cnavarro@utec.edu.pe'),
    ('CC1103', 'eanco@utec.edu.pe'),
    ('CC1103', 'hpantoja@utec.edu.pe'),
    ('CC1103', 'rperezc@utec.edu.pe'),
    ('CC1103', 'xchavez@utec.edu.pe'),
    ('CC1104', 'apena@utec.edu.pe'),
    ('CC1104', 'ctorresf@utec.edu.pe'),
    ('CC1104', 'preynoso@utec.edu.pe'),
    ('CC1105', 'agamero@utec.edu.pe'),
    ('CC1105', 'dgallo@utec.edu.pe'),
    ('CC1105', 'jrenom@utec.edu.pe'),
    ('CC1105', 'mprado@utec.edu.pe'),
    ('CC1105', 'msaenz@utec.edu.pe'),
    ('CC1105', 'ogalarza@utec.edu.pe'),
    ('CC1105', 'stanay@utec.edu.pe'),
    ('CC1122', 'elay@utec.edu.pe'),
    ('CC1122', 'jsanchezr@utec.edu.pe'),
    ('CC1122', 'mmendozaf@utec.edu.pe'),
    ('CC1123', 'mcuyubamba@utec.edu.pe'),
    ('CC1123', 'ocastillo@utec.edu.pe'),
    ('CC1141', 'mluna@utec.edu.pe'),
    ('CC1141', 'rhoyos@utec.edu.pe'),
    ('CC1142', 'cfranco@utec.edu.pe'),
    ('CC1143', 'arios@utec.edu.pe'),
    ('CC2101', 'cnavarro@utec.edu.pe'),
    ('CC2101', 'jgalvezg@utec.edu.pe'),
    ('CC2101', 'jsanchezr@utec.edu.pe'),
    ('CC2101', 'mcuyubamba@utec.edu.pe'),
    ('CC2101', 'nlopez@utec.edu.pe'),
    ('CC2101', 'preynoso@utec.edu.pe'),
    ('CC2102', 'ogalarza@utec.edu.pe'),
    ('CC2103', 'fvivanco@utec.edu.pe'),
    ('CC2104', 'jmendozam@utec.edu.pe'),
    ('CC2104', 'mcuyubamba@utec.edu.pe'),
    ('CC2104', 'preynoso@utec.edu.pe'),
    ('CC2104', 'rperezc@utec.edu.pe'),
    ('CC2106', 'fvivanco@utec.edu.pe'),
    ('CC2121', 'ctorresf@utec.edu.pe'),
    ('CC2121', 'nlopez@utec.edu.pe'),
    ('CC2121', 'nsanchezr@utec.edu.pe'),
    ('CC6101', 'ckhouri@utec.edu.pe'),
    ('CC6101', 'cnavarro@utec.edu.pe'),
    ('CC6101', 'crojas@utec.edu.pe'),
    ('CC6101', 'ctorresf@utec.edu.pe'),
    ('CC6101', 'jchiroque@utec.edu.pe'),
    ('CC6101', 'jnieves@utec.edu.pe'),
    ('CC6101', 'mcuyubamba@utec.edu.pe'),
    ('CC6101', 'volivera@utec.edu.pe'),
    ('CC6102', 'jnieves@utec.edu.pe'),
    ('CC6103', 'crojas@utec.edu.pe'),
    ('CC6103', 'eanco@utec.edu.pe'),
    ('CC6103', 'preynoso@utec.edu.pe'),
    ('CC6103', 'rperezc@utec.edu.pe'),
    ('CC6103', 'rseclen@utec.edu.pe'),
    ('CC6103', 'squispe@utec.edu.pe'),
    ('CC6103', 'volivera@utec.edu.pe'),
    ('CC6103', 'xchavez@utec.edu.pe'),
    ('CC6104', 'volivera@utec.edu.pe'),
    ('CC6105', 'eanco@utec.edu.pe'),
    ('CC6105', 'hpantoja@utec.edu.pe'),
    ('CC6105', 'jbarraza@utec.edu.pe'),
    ('CC6105', 'oortiz@utec.edu.pe'),
    ('CC6105', 'xchavez@utec.edu.pe'),
    ('CC6201', 'cmouls@utec.edu.pe'),
    ('CC6201', 'jsanchezr@utec.edu.pe'),
    ('CC6201', 'kzegarras@utec.edu.pe'),
    ('CC6201', 'ocastillo@utec.edu.pe'),
    ('CC6301', 'apinedo@utec.edu.pe'),
    ('CC6301', 'cfranco@utec.edu.pe'),
    ('CC6301', 'cterrones@utec.edu.pe'),
    ('CC6301', 'hcarcamo@utec.edu.pe'),
    ('CC6301', 'jgonzales@utec.edu.pe'),
    ('CC6301', 'layala@utec.edu.pe'),
    ('CC6301', 'rhoyos@utec.edu.pe'),
    ('CI2003', 'mfernandezch@utec.edu.pe'),
    ('CI2011', 'aostolaza@utec.edu.pe'),
    ('CI2011', 'cdiaze@utec.edu.pe'),
    ('CI2012', 'cdiaze@utec.edu.pe'),
    ('CI2031', 'ejuarez@utec.edu.pe'),
    ('CI3013', 'aostolaza@utec.edu.pe'),
    ('CI3014', 'aostolaza@utec.edu.pe'),
    ('CI3032', 'gperez@utec.edu.pe'),
    ('CI3032', 'rvasqueza@utec.edu.pe'),
    ('CI3033', 'msalas@utec.edu.pe'),
    ('CI3051', 'aarones@utec.edu.pe'),
    ('CI3071', 'cramos@utec.edu.pe'),
    ('CI3071', 'jmendozam@utec.edu.pe'),
    ('CI4034', 'hsuarezt@utec.edu.pe'),
    ('CI4035', 'hpineda@utec.edu.pe'),
    ('CI4052', 'mtincopa@utec.edu.pe'),
    ('CI4072', 'eguzman@utec.edu.pe'),
    ('CI4092', 'asanchezn@utec.edu.pe'),
    ('CI5006', 'cdiaze@utec.edu.pe'),
    ('CI5006', 'ejuarez@utec.edu.pe'),
    ('CI5006', 'gsotoc@utec.edu.pe'),
    ('CI5006', 'hpineda@utec.edu.pe'),
    ('CI5006', 'hsuarezt@utec.edu.pe'),
    ('CI5006', 'jorccosupa@utec.edu.pe'),
    ('CI5006', 'lbedrinana@utec.edu.pe'),
    ('CI5093', 'mfernandezch@utec.edu.pe'),
    ('CI5105', 'aostolaza@utec.edu.pe'),
    ('CI5105', 'asanchezn@utec.edu.pe'),
    ('CI5105', 'cbenedetty@utec.edu.pe'),
    ('CI5105', 'cdiaze@utec.edu.pe'),
    ('CI5105', 'ejuarez@utec.edu.pe'),
    ('CI5105', 'evereau@utec.edu.pe'),
    ('CI5105', 'hpineda@utec.edu.pe'),
    ('CI5105', 'hsuarezt@utec.edu.pe'),
    ('CI5105', 'mfernandezch@utec.edu.pe'),
    ('CI5105', 'mjara@utec.edu.pe'),
    ('CI5105', 'rgutierrezl@utec.edu.pe'),
    ('CI5311', 'cbenedetty@utec.edu.pe'),
    ('CI5312', 'cdiaze@utec.edu.pe'),
    ('CI5313', 'cdiaze@utec.edu.pe'),
    ('CI5314', 'aostolaza@utec.edu.pe'),
    ('CI5331', 'hsuarezt@utec.edu.pe'),
    ('CI5332', 'dpolanco@utec.edu.pe'),
    ('CI5333', 'ejuarez@utec.edu.pe'),
    ('CI5335', 'hsuarezt@utec.edu.pe'),
    ('CI5336', 'emejias@utec.edu.pe'),
    ('CI5351', 'lraygada@utec.edu.pe'),
    ('CI5353', 'lnunezn@utec.edu.pe'),
    ('CI5372', 'eguzman@utec.edu.pe'),
    ('CI5373', 'mjara@utec.edu.pe'),
    ('CI5391', 'mfernandezch@utec.edu.pe'),
    ('CI5394', 'wsamaniego@utec.edu.pe'),
    ('CI5395', 'wsamaniego@utec.edu.pe'),
    ('CI5396', 'rrojasma@utec.edu.pe'),
    ('CI6101', 'hsuarezt@utec.edu.pe'),
    ('CI6102', 'kvilela@utec.edu.pe'),
    ('CS2013', 'jchaveza@utec.edu.pe'),
    ('CS2013', 'rrivas@utec.edu.pe'),
    ('CS2023', 'lromeroc@utec.edu.pe'),
    ('CS2023', 'vgalvan@utec.edu.pe'),
    ('CS2023', 'wnina@utec.edu.pe'),
    ('CS2031', 'jvillavicencio@utec.edu.pe'),
    ('CS2031', 'jyarascam@utec.edu.pe'),
    ('CS2031', 'plovon@utec.edu.pe'),
    ('CS2032', 'gcolchado@utec.edu.pe'),
    ('CS2032', 'omejia@utec.edu.pe'),
    ('CS2041', 'bojeda@utec.edu.pe'),
    ('CS2041', 'wnina@utec.edu.pe'),
    ('CS2042', 'hsanchez@utec.edu.pe'),
    ('CS2042', 'plovon@utec.edu.pe'),
    ('CS3014', 'vgalvan@utec.edu.pe'),
    ('CS3015', 'jgonzalez@utec.edu.pe'),
    ('CS3025', 'jyarascam@utec.edu.pe'),
    ('CS3026', 'jgalva@utec.edu.pe'),
    ('CS3026', 'vgalvan@utec.edu.pe'),
    ('CS3033', 'vgalvan@utec.edu.pe'),
    ('CS3051', 'cwilliams@utec.edu.pe'),
    ('CS3051', 'jgonzalez@utec.edu.pe'),
    ('CS3051', 'ladanaque@utec.edu.pe'),
    ('CS3061', 'vmartinez@utec.edu.pe'),
    ('CS3081', 'tchambilla@utec.edu.pe'),
    ('CS4052', 'jfiestas@utec.edu.pe'),
    ('CS4053', 'tchambilla@utec.edu.pe'),
    ('CS4054', 'cwilliams@utec.edu.pe'),
    ('CS4054', 'garias@utec.edu.pe'),
    ('CS5011', 'avillegass@utec.edu.pe'),
    ('CS5011', 'bojeda@utec.edu.pe'),
    ('CS5011', 'clopezd@utec.edu.pe'),
    ('CS5011', 'ctenorio@utec.edu.pe'),
    ('CS5011', 'ebiagioli@utec.edu.pe'),
    ('CS5011', 'ecayllahua@utec.edu.pe'),
    ('CS5011', 'jchaveza@utec.edu.pe'),
    ('CS5011', 'jfiestas@utec.edu.pe'),
    ('CS5011', 'jgonzalez@utec.edu.pe'),
    ('CS5011', 'ladanaque@utec.edu.pe'),
    ('CS5011', 'lromeroc@utec.edu.pe'),
    ('CS5011', 'rmora@utec.edu.pe'),
    ('CS5011', 'vflores@utec.edu.pe'),
    ('CS5011', 'vmartinez@utec.edu.pe'),
    ('CS5055', 'cwilliams@utec.edu.pe'),
    ('CS5055', 'garias@utec.edu.pe'),
    ('CS5101', 'avillegass@utec.edu.pe'),
    ('CS5101', 'bojeda@utec.edu.pe'),
    ('CS5101', 'clopezd@utec.edu.pe'),
    ('CS5101', 'ctenorio@utec.edu.pe'),
    ('CS5101', 'ebiagioli@utec.edu.pe'),
    ('CS5101', 'ecayllahua@utec.edu.pe'),
    ('CS5101', 'hgallegos@utec.edu.pe'),
    ('CS5101', 'jchaveza@utec.edu.pe'),
    ('CS5101', 'jfiestas@utec.edu.pe'),
    ('CS5101', 'jgonzalez@utec.edu.pe'),
    ('CS5101', 'ladanaque@utec.edu.pe'),
    ('CS5101', 'lromeroc@utec.edu.pe'),
    ('CS5101', 'rmora@utec.edu.pe'),
    ('CS5101', 'tchambilla@utec.edu.pe'),
    ('CS5101', 'vflores@utec.edu.pe'),
    ('CS5101', 'vmartinez@utec.edu.pe'),
    ('CS5101', 'wnina@utec.edu.pe'),
    ('CS5351', 'ebiagioli@utec.edu.pe'),
    ('CS5352', 'lromeroc@utec.edu.pe'),
    ('CS5362', 'rmora@utec.edu.pe'),
    ('CS5362', 'vmandujano@utec.edu.pe'),
    ('CS5363', 'asoriano@utec.edu.pe'),
    ('CS5364', 'vflores@utec.edu.pe'),
    ('CS5365', 'jchaveza@utec.edu.pe'),
    ('CS5371', 'jpazos@utec.edu.pe'),
    ('CS5373', 'lgastulo@utec.edu.pe'),
    ('CS5382', 'cbalbuena@utec.edu.pe'),
    ('CS5383', 'crojasb@utec.edu.pe'),
    ('CS5384', 'gpajuelo@utec.edu.pe'),
    ('CS5392', 'jgutierreza@utec.edu.pe'),
    ('CS6001', 'ibrossard@utec.edu.pe'),
    ('CS6002', 'agarciar@utec.edu.pe'),
    ('CS6002', 'hgallegos@utec.edu.pe'),
    ('CS6002', 'jcumpa@utec.edu.pe'),
    ('CS6002', 'jyarascam@utec.edu.pe'),
    ('CS6002', 'mbermejo@utec.edu.pe'),
    ('CS6003', 'hgallegos@utec.edu.pe'),
    ('CS6003', 'ibrossard@utec.edu.pe'),
    ('CS6003', 'vmandujano@utec.edu.pe'),
    ('CS6003', 'wnina@utec.edu.pe'),
    ('CS6004', 'vmandujano@utec.edu.pe'),
    ('CS6005', 'dsanchezr@utec.edu.pe'),
    ('CS6005', 'etaipe@utec.edu.pe'),
    ('CS6005', 'jtipe@utec.edu.pe'),
    ('CS6005', 'lperes@utec.edu.pe'),
    ('CS6006', 'dsanchezr@utec.edu.pe'),
    ('CS6006', 'lperes@utec.edu.pe'),
    ('CS6006', 'rmas@utec.edu.pe'),
    ('CY6001', 'jpazos@utec.edu.pe'),
    ('CY6001', 'lponce@utec.edu.pe'),
    ('DS2011', 'vtorres@utec.edu.pe'),
    ('DS3012', 'jugarte@utec.edu.pe'),
    ('DS3021', 'jespinozame@utec.edu.pe'),
    ('DS3022', 'ggarciaz@utec.edu.pe'),
    ('DS3031', 'jpazos@utec.edu.pe'),
    ('DS4051', 'mgarciat@utec.edu.pe'),
    ('DS4061', 'dchira@utec.edu.pe'),
    ('DS4061', 'mgarciat@utec.edu.pe'),
    ('DS4341', 'alezama@utec.edu.pe'),
    ('DS5012', 'acardenasm@utec.edu.pe'),
    ('DS5012', 'asoriano@utec.edu.pe'),
    ('DS5012', 'ggarciaz@utec.edu.pe'),
    ('DS5012', 'rmora@utec.edu.pe'),
    ('DS5044', 'ytupac@utec.edu.pe'),
    ('DS5102', 'acardenasm@utec.edu.pe'),
    ('DS5102', 'jgalva@utec.edu.pe'),
    ('DS5102', 'rmora@utec.edu.pe'),
    ('DS5342', 'hsanchez@utec.edu.pe'),
    ('DS5343', 'ggarciaz@utec.edu.pe'),
    ('DS5344', 'cbalbuena@utec.edu.pe'),
    ('DS5345', 'plovon@utec.edu.pe'),
    ('DS5346', 'vflores@utec.edu.pe'),
    ('EL2011', 'jzavalac@utec.edu.pe'),
    ('EL2011', 'lquineche@utec.edu.pe'),
    ('EL2012', 'gmichhue@utec.edu.pe'),
    ('EL2012', 'mbelen@utec.edu.pe'),
    ('EL2013', 'ahinostroza@utec.edu.pe'),
    ('EL2013', 'cbriceno@utec.edu.pe'),
    ('EL2013', 'fcamacho@utec.edu.pe'),
    ('EL2013', 'gmichhue@utec.edu.pe'),
    ('EL2013', 'gpatino@utec.edu.pe'),
    ('EL2013', 'pcrisostomo@utec.edu.pe'),
    ('EL2014', 'iyupanqui@utec.edu.pe'),
    ('EL2014', 'lquineche@utec.edu.pe'),
    ('EL2081', 'camaya@utec.edu.pe'),
    ('EL2081', 'earellanos@utec.edu.pe'),
    ('EL2081', 'fcamacho@utec.edu.pe'),
    ('EL2081', 'jzavalac@utec.edu.pe'),
    ('EL2081', 'mlozano@utec.edu.pe'),
    ('EL2082', 'acespedes@utec.edu.pe'),
    ('EL2082', 'mlozano@utec.edu.pe'),
    ('EL3011', 'fcamacho@utec.edu.pe'),
    ('EL3012', 'dhuamanchahua@utec.edu.pe'),
    ('EL3012', 'hvalcarcel@utec.edu.pe'),
    ('EL3012', 'jbautista@utec.edu.pe'),
    ('EL3013', 'cflores@utec.edu.pe'),
    ('EL3013', 'jfabianl@utec.edu.pe'),
    ('EL3014', 'fcamacho@utec.edu.pe'),
    ('EL3014', 'gpatino@utec.edu.pe'),
    ('EL3014', 'jtarrillo@utec.edu.pe'),
    ('EL3014', 'nnunovero@utec.edu.pe'),
    ('EL3015', 'mnunez@utec.edu.pe'),
    ('EL3016', 'gmichhue@utec.edu.pe'),
    ('EL3016', 'jlezama@utec.edu.pe'),
    ('EL3016', 'mclemente@utec.edu.pe'),
    ('EL3301', 'acespedes@utec.edu.pe'),
    ('EL3301', 'lgarciaz@utec.edu.pe'),
    ('EL3301', 'saranda@utec.edu.pe'),
    ('EL3302', 'jfarfan@utec.edu.pe'),
    ('EL3303', 'agutarra@utec.edu.pe'),
    ('EL3303', 'dinga@utec.edu.pe'),
    ('EL3303', 'smorales@utec.edu.pe'),
    ('EL3304', 'jfarfan@utec.edu.pe'),
    ('EL4011', 'cmonterrey@utec.edu.pe'),
    ('EL4011', 'mlozano@utec.edu.pe'),
    ('EL4012', 'lvolodina@utec.edu.pe'),
    ('EL4013', 'framirez@utec.edu.pe'),
    ('EL4301', 'cdiazp@utec.edu.pe'),
    ('EL4301', 'lgarciaz@utec.edu.pe'),
    ('EL4301', 'rcabrerad@utec.edu.pe'),
    ('EL4302', 'cbriceno@utec.edu.pe'),
    ('EL4302', 'jtarrillo@utec.edu.pe'),
    ('EL5006', 'cflores@utec.edu.pe'),
    ('EL5006', 'mlozano@utec.edu.pe'),
    ('EL5006', 'mnunez@utec.edu.pe'),
    ('EL5006', 'saranda@utec.edu.pe'),
    ('EL5102', 'aduenas@utec.edu.pe'),
    ('EL5102', 'jtarrillo@utec.edu.pe'),
    ('EL5102', 'lvolodina@utec.edu.pe'),
    ('EL5102', 'saranda@utec.edu.pe'),
    ('EL5302', 'mclemente@utec.edu.pe'),
    ('EL5303', 'conaka@utec.edu.pe'),
    ('EL5304', 'saranda@utec.edu.pe'),
    ('EL5305', 'cdiazp@utec.edu.pe'),
    ('EL5305', 'spalomino@utec.edu.pe'),
    ('EL5306', 'djara@utec.edu.pe'),
    ('EL5306', 'lcastillo@utec.edu.pe'),
    ('EL5307', 'framirez@utec.edu.pe'),
    ('EL5308', 'gmichhue@utec.edu.pe'),
    ('EL5309', 'jlezama@utec.edu.pe'),
    ('EL5309', 'mclemente@utec.edu.pe'),
    ('EL5311', 'conaka@utec.edu.pe'),
    ('EL5311', 'mnunez@utec.edu.pe'),
    ('EL5312', 'smorales@utec.edu.pe'),
    ('EL5313', 'pcrisostomo@utec.edu.pe'),
    ('EL5319', 'framirez@utec.edu.pe'),
    ('EL6011', 'fcamacho@utec.edu.pe'),
    ('EL6011', 'mlozano@utec.edu.pe'),
    ('EN2011', 'rvera@utec.edu.pe'),
    ('EN2013', 'rescudero@utec.edu.pe'),
    ('EN2014', 'paraujo@utec.edu.pe'),
    ('EN3011', 'rescudero@utec.edu.pe'),
    ('EN3012', 'rescudero@utec.edu.pe'),
    ('EN3013', 'jmaravi@utec.edu.pe'),
    ('EN3014', 'wramosv@utec.edu.pe'),
    ('EN3015', 'rescudero@utec.edu.pe'),
    ('EN3016', 'jramos@utec.edu.pe'),
    ('EN3017', 'vnunez@utec.edu.pe'),
    ('EN3018', 'eramirez@utec.edu.pe'),
    ('EN4011', 'eramirez@utec.edu.pe'),
    ('EN4012', 'jmaravi@utec.edu.pe'),
    ('EN4013', 'lpinto@utec.edu.pe'),
    ('EN4014', 'dvilcat@utec.edu.pe'),
    ('EN5004', 'jramos@utec.edu.pe'),
    ('EN5004', 'rescudero@utec.edu.pe'),
    ('EN5004', 'rvera@utec.edu.pe'),
    ('EN5101', 'eramirez@utec.edu.pe'),
    ('EN5101', 'paraujo@utec.edu.pe'),
    ('EN5101', 'rvera@utec.edu.pe'),
    ('EN5302', 'rvera@utec.edu.pe'),
    ('EN5303', 'rvera@utec.edu.pe'),
    ('EN5304', 'rliy@utec.edu.pe'),
    ('EN5305', 'rliy@utec.edu.pe'),
    ('EN5306', 'paraujo@utec.edu.pe'),
    ('EN5307', 'jramos@utec.edu.pe'),
    ('EN5309', 'rliy@utec.edu.pe'),
    ('EN5401', 'xguardia@utec.edu.pe'),
    ('EN5403', 'lpinto@utec.edu.pe'),
    ('EN5404', 'jmaravi@utec.edu.pe'),
    ('EN6101', 'jchiroque@utec.edu.pe'),
    ('GH0023', 'kneira@utec.edu.pe'),
    ('GI2101', 'cguevara@utec.edu.pe'),
    ('GI2101', 'jvalencia@utec.edu.pe'),
    ('GI2101', 'rcondorena@utec.edu.pe'),
    ('GI2101', 'ycentty@utec.edu.pe'),
    ('GI3101', 'jcastillor@utec.edu.pe'),
    ('GI3101', 'jsanchez@utec.edu.pe'),
    ('GI3101', 'lobispo@utec.edu.pe'),
    ('GI3101', 'marauco@utec.edu.pe'),
    ('GI3101', 'mvelasquez@utec.edu.pe'),
    ('GI3201', 'cgutierrezz@utec.edu.pe'),
    ('GI4101', 'cgutierrezz@utec.edu.pe'),
    ('GI4101', 'dramirez@utec.edu.pe'),
    ('GI4101', 'jaguilar@utec.edu.pe'),
    ('GI4101', 'jcastillor@utec.edu.pe'),
    ('GI4101', 'jespinozam@utec.edu.pe'),
    ('GI4101', 'jsanchez@utec.edu.pe'),
    ('GI4101', 'mvelasquez@utec.edu.pe'),
    ('GI5101', 'aestrada@utec.edu.pe'),
    ('GI5101', 'exicota@utec.edu.pe'),
    ('GI5101', 'jespinozam@utec.edu.pe'),
    ('GI5101', 'jherran@utec.edu.pe'),
    ('GI5101', 'jramirezb@utec.edu.pe'),
    ('GI5101', 'jvalencia@utec.edu.pe'),
    ('GI5101', 'mtoro@utec.edu.pe'),
    ('GI5101', 'ovento@utec.edu.pe'),
    ('HH2101', 'aescudero@utec.edu.pe'),
    ('HH2101', 'anunezd@utec.edu.pe'),
    ('HH2101', 'ebaca@utec.edu.pe'),
    ('HH2101', 'gespinozad@utec.edu.pe'),
    ('HH2101', 'jpino@utec.edu.pe'),
    ('HH2101', 'mstiglich@utec.edu.pe'),
    ('HH2102', 'anunezd@utec.edu.pe'),
    ('HH2102', 'gespinozad@utec.edu.pe'),
    ('HH2102', 'kchuspe@utec.edu.pe'),
    ('HH2102', 'lsanchezp@utec.edu.pe'),
    ('HH2102', 'nbonopaladino@utec.edu.pe'),
    ('HH2201', 'cmarquez@utec.edu.pe'),
    ('HH2202', 'galexandrino@utec.edu.pe'),
    ('HH2204', 'csagastegui@utec.edu.pe'),
    ('HH2205', 'adelaflor@utec.edu.pe'),
    ('HH2206', 'cmarquez@utec.edu.pe'),
    ('HH2207', 'vramirez@utec.edu.pe'),
    ('HH3101', 'adelaflor@utec.edu.pe'),
    ('HH3101', 'ahopkins@utec.edu.pe'),
    ('HH3101', 'calayza@utec.edu.pe'),
    ('HH3101', 'dcastillo@utec.edu.pe'),
    ('HH3101', 'ggarcia@utec.edu.pe'),
    ('HH3101', 'icollazos@utec.edu.pe'),
    ('HH3201', 'cmarquez@utec.edu.pe'),
    ('HH4201', 'acalderon@utec.edu.pe'),
    ('HH4203', 'ohidalgo@utec.edu.pe'),
    ('HH5001', 'exicota@utec.edu.pe'),
    ('HH5101', 'amillan@utec.edu.pe'),
    ('HH5101', 'calayza@utec.edu.pe'),
    ('HH5101', 'ddavila@utec.edu.pe'),
    ('HH5101', 'jarana@utec.edu.pe'),
    ('HH5101', 'roliart@utec.edu.pe'),
    ('HH6001', 'ccabezas@utec.edu.pe'),
    ('HH6001', 'czorrilla@utec.edu.pe'),
    ('HH6001', 'dcespedesc@utec.edu.pe'),
    ('HH6001', 'dgonzales@utec.edu.pe'),
    ('HH6001', 'gacosta@utec.edu.pe'),
    ('HH6001', 'jmunoz@utec.edu.pe'),
    ('HH6001', 'ohidalgo@utec.edu.pe'),
    ('HH6001', 'treyes@utec.edu.pe'),
    ('HH6001', 'vramirez@utec.edu.pe'),
    ('HH6002', 'gacosta@utec.edu.pe'),
    ('HH6002', 'ohidalgo@utec.edu.pe'),
    ('HH6002', 'treyes@utec.edu.pe'),
    ('HH6002', 'vcaballero@utec.edu.pe'),
    ('HH6002', 'vramirez@utec.edu.pe'),
    ('IN2003', 'fcornillier@utec.edu.pe'),
    ('IN2003', 'lfloresl@utec.edu.pe'),
    ('IN2004', 'jdelapuente@utec.edu.pe'),
    ('IN2004', 'ocanasas@utec.edu.pe'),
    ('IN2005', 'cantonini@utec.edu.pe'),
    ('IN2005', 'ogalarza@utec.edu.pe'),
    ('IN3003', 'cnunura@utec.edu.pe'),
    ('IN3003', 'fcamacho@utec.edu.pe'),
    ('IN3004', 'uvelazco@utec.edu.pe'),
    ('IN3005', 'fcornillier@utec.edu.pe'),
    ('IN3006', 'qmeza@utec.edu.pe'),
    ('IN3007', 'ggonzales@utec.edu.pe'),
    ('IN3007', 'qmeza@utec.edu.pe'),
    ('IN3008', 'ogamonal@utec.edu.pe'),
    ('IN3009', 'jbueno@utec.edu.pe'),
    ('IN3010', 'jbueno@utec.edu.pe'),
    ('IN3011', 'cantonini@utec.edu.pe'),
    ('IN3012', 'ggonzales@utec.edu.pe'),
    ('IN3012', 'ogamonal@utec.edu.pe'),
    ('IN4007', 'jgranadoso@utec.edu.pe'),
    ('IN4007', 'qmeza@utec.edu.pe'),
    ('IN4008', 'jcerda@utec.edu.pe'),
    ('IN4009', 'clegua@utec.edu.pe'),
    ('IN4301', 'dhernandezs@utec.edu.pe'),
    ('IN4302', 'lrodriguezw@utec.edu.pe'),
    ('IN4304', 'cramirezl@utec.edu.pe'),
    ('IN4305', 'ogamonal@utec.edu.pe'),
    ('IN5007', 'lfloresl@utec.edu.pe'),
    ('IN5008', 'sarevalo@utec.edu.pe'),
    ('IN5011', 'cantonini@utec.edu.pe'),
    ('IN5011', 'gpella@utec.edu.pe'),
    ('IN5011', 'jbueno@utec.edu.pe'),
    ('IN5011', 'jdelapuente@utec.edu.pe'),
    ('IN5011', 'jugarte@utec.edu.pe'),
    ('IN5011', 'lfloresl@utec.edu.pe'),
    ('IN5107', 'ggonzales@utec.edu.pe'),
    ('IN5107', 'gpella@utec.edu.pe'),
    ('IN5107', 'jdelapuente@utec.edu.pe'),
    ('IN5107', 'jinga@utec.edu.pe'),
    ('IN5107', 'jugarte@utec.edu.pe'),
    ('IN5107', 'lvolodina@utec.edu.pe'),
    ('IN5301', 'vzuniga@utec.edu.pe'),
    ('IN5302', 'jarteagacu@utec.edu.pe'),
    ('IN5304', 'lgomez@utec.edu.pe'),
    ('IN5306', 'jvillavicencio@utec.edu.pe'),
    ('IN5309', 'gpella@utec.edu.pe'),
    ('IN5310', 'ggonzales@utec.edu.pe'),
    ('IN6011', 'qmeza@utec.edu.pe'),
    ('IN6012', 'ogamonal@utec.edu.pe'),
    ('IN6012', 'qmeza@utec.edu.pe'),
    ('IQ2001', 'aflores@utec.edu.pe'),
    ('IQ2001', 'echavez@utec.edu.pe'),
    ('IQ2002', 'cfloresb@utec.edu.pe'),
    ('IQ2003', 'ftarazona@utec.edu.pe'),
    ('IQ2003', 'wramosv@utec.edu.pe'),
    ('IQ3001', 'mchuman@utec.edu.pe'),
    ('IQ3002', 'wramosv@utec.edu.pe'),
    ('IQ3003', 'dparada@utec.edu.pe'),
    ('IQ3003', 'mchuman@utec.edu.pe'),
    ('IQ3004', 'azuniga@utec.edu.pe'),
    ('IQ3004', 'mcarranza@utec.edu.pe'),
    ('IQ3005', 'lvargas@utec.edu.pe'),
    ('IQ3006', 'kgonzales@utec.edu.pe'),
    ('IQ3006', 'mchuman@utec.edu.pe'),
    ('IQ4001', 'aflores@utec.edu.pe'),
    ('IQ4002', 'vfigueroa@utec.edu.pe'),
    ('IQ4003', 'jbanon@utec.edu.pe'),
    ('IQ4003', 'mcarranza@utec.edu.pe'),
    ('IQ4004', 'gmamani@utec.edu.pe'),
    ('IQ4222', 'jguerrero@utec.edu.pe'),
    ('IQ4222', 'vfigueroa@utec.edu.pe'),
    ('IQ5001', 'ccaceres@utec.edu.pe'),
    ('IQ5001', 'jbanon@utec.edu.pe'),
    ('IQ5002', 'aflores@utec.edu.pe'),
    ('IQ5003', 'etejada@utec.edu.pe'),
    ('IQ5333', 'hames@utec.edu.pe'),
    ('IQ5333', 'uquiroz@utec.edu.pe'),
    ('IQ5334', 'vmadrid@utec.edu.pe'),
    ('IQ5335', 'azuniga@utec.edu.pe'),
    ('IQ5335', 'nlopez@utec.edu.pe'),
    ('IQ5336', 'jguerrero@utec.edu.pe'),
    ('IQ6001', 'lvargas@utec.edu.pe'),
    ('IQ6002', 'aflores@utec.edu.pe'),
    ('IQ6002', 'echavez@utec.edu.pe'),
    ('IS2011', 'dchira@utec.edu.pe'),
    ('IS2021', 'ladanaque@utec.edu.pe'),
    ('IS3012', 'kcelis@utec.edu.pe'),
    ('IS4024', 'wjulca@utec.edu.pe'),
    ('IS5201', 'kruiz@utec.edu.pe'),
    ('IS5202', 'acardenasm@utec.edu.pe'),
    ('IS5203', 'ctenorio@utec.edu.pe'),
    ('IS5205', 'acardenasm@utec.edu.pe'),
    ('IS6001', 'ctenorio@utec.edu.pe'),
    ('ME2012', 'scandiotti@utec.edu.pe'),
    ('ME2013', 'scandiotti@utec.edu.pe'),
    ('ME2013', 'vorihuela@utec.edu.pe'),
    ('ME2014', 'scandiotti@utec.edu.pe'),
    ('ME3011', 'jmendozam@utec.edu.pe'),
    ('ME3012', 'aperalta@utec.edu.pe'),
    ('ME3012', 'scharca@utec.edu.pe'),
    ('ME3013', 'cnunura@utec.edu.pe'),
    ('ME3014', 'eramirez@utec.edu.pe'),
    ('ME3015', 'halvarez@utec.edu.pe'),
    ('ME3016', 'jsanchezs@utec.edu.pe'),
    ('ME3017', 'vorihuela@utec.edu.pe'),
    ('ME4011', 'jsanchezs@utec.edu.pe'),
    ('ME5007', 'halvarez@utec.edu.pe'),
    ('ME5007', 'jguerrero@utec.edu.pe'),
    ('ME5007', 'obejarano@utec.edu.pe'),
    ('ME5007', 'scharca@utec.edu.pe'),
    ('ME5007', 'vorihuela@utec.edu.pe'),
    ('ME5104', 'halvarez@utec.edu.pe'),
    ('ME5104', 'mwdkim@utec.edu.pe'),
    ('ME5104', 'obejarano@utec.edu.pe'),
    ('ME5104', 'paraujo@utec.edu.pe'),
    ('ME5104', 'vorihuela@utec.edu.pe'),
    ('ME5301', 'jguerrero@utec.edu.pe'),
    ('ME5302', 'japaza@utec.edu.pe'),
    ('ME5303', 'japaza@utec.edu.pe'),
    ('ME5304', 'vorihuela@utec.edu.pe'),
    ('ME5305', 'lhurtadoc@utec.edu.pe'),
    ('ME5306', 'lhurtadoc@utec.edu.pe'),
    ('ME5307', 'cnunura@utec.edu.pe'),
    ('ME5308', 'halvarez@utec.edu.pe'),
    ('ME5310', 'cnunura@utec.edu.pe'),
    ('ME5312', 'mwdkim@utec.edu.pe'),
    ('ME5313', 'mwdkim@utec.edu.pe'),
    ('ME5314', 'mwdkim@utec.edu.pe'),
    ('ME5402', 'jguerrero@utec.edu.pe'),
    ('ME6101', 'volivera@utec.edu.pe'),
    ('ME6102', 'jmorales@utec.edu.pe'),
    ('ME6102', 'volivera@utec.edu.pe'),
    ('MT2001', 'jbohorquez@utec.edu.pe'),
    ('MT2001', 'wbarrutia@utec.edu.pe'),
    ('MT3001', 'lgarciaz@utec.edu.pe'),
    ('MT3001', 'rmiranda@utec.edu.pe'),
    ('MT3001', 'spalomino@utec.edu.pe'),
    ('MT4001', 'jcallupe@utec.edu.pe'),
    ('MT4001', 'jlopezm@utec.edu.pe'),
    ('MT4002', 'rcabrerad@utec.edu.pe'),
    ('MT4002', 'rmiranda@utec.edu.pe'),
    ('MT4002', 'spalomino@utec.edu.pe'),
    ('MT4003', 'ejara@utec.edu.pe'),
    ('MT4003', 'pfloresa@utec.edu.pe'),
    ('MT5001', 'ejara@utec.edu.pe'),
    ('MT5001', 'jmagallanesc@utec.edu.pe'),
    ('MT5001', 'mpuchuri@utec.edu.pe'),
    ('MT5003', 'cflores@utec.edu.pe'),
    ('MT5003', 'dhuamanchahua@utec.edu.pe'),
    ('MT5003', 'dinga@utec.edu.pe'),
    ('MT5003', 'ejara@utec.edu.pe'),
    ('MT5003', 'jcallupe@utec.edu.pe'),
    ('MT5003', 'jtapullima@utec.edu.pe'),
    ('MT5003', 'rcabrerad@utec.edu.pe'),
    ('MT5003', 'wbarrutia@utec.edu.pe'),
    ('MT5103', 'dinga@utec.edu.pe'),
    ('MT5103', 'iyupanqui@utec.edu.pe'),
    ('MT5103', 'jtarrillo@utec.edu.pe'),
    ('MT5103', 'lvolodina@utec.edu.pe'),
    ('MT5103', 'rcabrerad@utec.edu.pe'),
    ('MT5103', 'wbarrutia@utec.edu.pe'),
    ('MT5305', 'jlopezm@utec.edu.pe'),
    ('MT5305', 'oramos@utec.edu.pe'),
    ('MT5306', 'lgarciaz@utec.edu.pe'),
    ('MT5306', 'rcabrerad@utec.edu.pe'),
    ('MT5307', 'agutarra@utec.edu.pe'),
    ('MT5307', 'iyupanqui@utec.edu.pe'),
    ('MT5312', 'jfabianl@utec.edu.pe'),
    ('MT5313', 'jtapullima@utec.edu.pe'),
    ('MT6011', 'molortegui@utec.edu.pe'),
    ('MT6011', 'nrojas@utec.edu.pe'),
    ('MT6011', 'spalomino@utec.edu.pe'),
    ('PI3103', 'aestrada@utec.edu.pe'),
    ('PI3103', 'cpereira@utec.edu.pe'),
    ('PI3103', 'czorrilla@utec.edu.pe'),
    ('PI3103', 'gpella@utec.edu.pe'),
    ('PI3103', 'jgonzales@utec.edu.pe'),
    ('PI3103', 'jmoranj@utec.edu.pe'),
    ('PI3103', 'jsanchez@utec.edu.pe'),
    ('PI3103', 'jvelarde@utec.edu.pe'),
    ('PI3103', 'lvolodina@utec.edu.pe'),
    ('PI3103', 'szamora@utec.edu.pe'),
    ('PI3103', 'vfreundt@utec.edu.pe'),
    ('PI6001', 'adelaflor@utec.edu.pe'),
    ('PI6001', 'adeleo@utec.edu.pe'),
    ('PI6001', 'amackay@utec.edu.pe'),
    ('PI6001', 'amillan@utec.edu.pe'),
    ('PI6001', 'ebaca@utec.edu.pe'),
    ('PI6001', 'fburneo@utec.edu.pe'),
    ('PI6001', 'galexandrino@utec.edu.pe'),
    ('PI6001', 'gespinozad@utec.edu.pe'),
    ('PI6001', 'ggarcia@utec.edu.pe'),
    ('PI6001', 'jmunoz@utec.edu.pe'),
    ('PI6001', 'jpino@utec.edu.pe'),
    ('PI6001', 'mdelcastillo@utec.edu.pe'),
    ('PI6001', 'mstiglich@utec.edu.pe'),
    ('PI6001', 'smontoya@utec.edu.pe'),
    ('PI6002', 'earellanos@utec.edu.pe'),
    ('PI6002', 'fcastillo@utec.edu.pe'),
    ('PI6002', 'jbohorquez@utec.edu.pe'),
    ('PI6002', 'jpaucara@utec.edu.pe'),
    ('PI6002', 'jvelarde@utec.edu.pe'),
    ('PI6002', 'nrojas@utec.edu.pe'),
    ('PI6002', 'oortiz@utec.edu.pe'),
    ('PI6002', 'rtorresa@utec.edu.pe'),
    ('QI5010', 'urodriguez@utec.edu.pe'),
    ('QI5109', 'aflores@utec.edu.pe'),
    ('QI5109', 'etejada@utec.edu.pe'),
    ('QI5109', 'mcarranza@utec.edu.pe')
  );
